# Subgroup Analysis

Subgroup analysis is performed within the ITT population during the baseline period to identify variables for potential stratification or adjustment.  The mean and standard deviation, as well as median and interquartile range (IQR), of the daily duration of each behavior during the baseline period will be calculated for population subgroups (without regard to study group) and statistical tests to identify behaviors that differ significantly across groups are performed.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
pd.set_option('display.max_rows', 700)
pd.set_option('display.max_columns', 700)
from statsmodels.iolib.table import SimpleTable

In [2]:
data_additional_metric = pd.read_csv("gs://hpn_cte_advanced_stats_data_repository/yahui_data_repository/Aging 202312/AGING_DATA_EXTRACT__NEW_NQSD_20231214.csv")
population = pd.read_csv("gs://hpn_cte_advanced_stats_data_repository/yahui_data_repository/Aging 202312/population_updates_20231214.csv")

/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3258: DtypeWarning: Columns (640,642,646,653) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data_additional_metric.head()

,PET_ID,EXTERNAL_ID,DEVICE_ID,STUDY_ID,STUDY_NAME,PET_NAME,DATE,NORMALIZED_STUDY_DAY,NORMALIZED_QUALIFYING_STUDY_DAY,STUDY_DAY_COUNTER,STUDY_GROUP,BASELINE_START,START_DATE,ENROLLMENT_DATE,COMPLETION_DATE,END_DATE,EXCESSIVE_RUNNING,TIMEZONE,QUALIFYING_DATA_DAY,IS_QUALIFIED,DAILYDATAQUALITYINDREASON,VAR_TD_1_Q1_2,VAR_CE_1_Q1_2,VAR_MIN_1_Q1_2,VAR_MED_1_Q1_2,VAR_RANG_1_Q1_2,VAR_MAX_1_Q1_2,VAR_AVG_1_Q1_2,VAR_SD_1_Q1_2,VAR_IQR_1_Q1_2,VAR_ACE_1_Q1_2,VAR_SDCE_1_Q1_2,VAR_IQRCE_1_Q1_2,VAR_CE3SD_1_Q1_2,VAR_TD_3_Q1_2,VAR_CE_3_Q1_2,VAR_MIN_3_Q1_2,VAR_MED_3_Q1_2,VAR_RANG_3_Q1_2,VAR_MAX_3_Q1_2,VAR_AVG_3_Q1_2,VAR_SD_3_Q1_2,VAR_IQR_3_Q1_2,VAR_ACE_3_Q1_2,VAR_SDCE_3_Q1_2,VAR_IQRCE_3_Q1_2,VAR_CE3SD_3_Q1_2,VAR_TD_5_Q1_2,VAR_CE_5_Q1_2,VAR_MIN_5_Q1_2,VAR_MED_5_Q1_2,VAR_RANG_5_Q1_2,VAR_MAX_5_Q1_2,VAR_AVG_5_Q1_2,VAR_SD_5_Q1_2,VAR_IQR_5_Q1_2,VAR_ACE_5_Q1_2,VAR_SDCE_5_Q1_2,VAR_IQRCE_5_Q1_2,VAR_CE3SD_5_Q1_2,VAR_TD_4_Q1_2,VAR_CE_4_Q1_2,VAR_MIN_4_Q1_2,VAR_MED_4_Q1_2,VAR_RANG_4_Q1_2,VAR_MAX_4_Q1_2,VAR_AVG_4_Q1_2,VAR_SD_4_Q1_2,VAR_IQR_4_Q1_2,VAR_ACE_4_Q1_2,VAR_SDCE_4_Q1_2,VAR_IQRCE_4_Q1_2,VAR_CE3SD_4_Q1_2,VAR_TD_12_Q1_2,VAR_CE_12_Q1_2,VAR_MIN_12_Q1_2,VAR_MED_12_Q1_2,VAR_RANG_12_Q1_2,VAR_MAX_12_Q1_2,VAR_AVG_12_Q1_2,VAR_SD_12_Q1_2,VAR_IQR_12_Q1_2,VAR_ACE_12_Q1_2,VAR_SDCE_12_Q1_2,VAR_IQRCE_12_Q1_2,VAR_CE3SD_12_Q1_2,VAR_TD_2_Q1_2,VAR_CE_2_Q1_2,VAR_MIN_2_Q1_2,VAR_MED_2_Q1_2,VAR_RANG_2_Q1_2,VAR_MAX_2_Q1_2,VAR_AVG_2_Q1_2,VAR_SD_2_Q1_2,VAR_IQR_2_Q1_2,VAR_ACE_2_Q1_2,VAR_SDCE_2_Q1_2,VAR_IQRCE_2_Q1_2,VAR_CE3SD_2_Q1_2,VAR_TD_46_Q1_2,VAR_CE_46_Q1_2,VAR_MIN_46_Q1_2,VAR_MED_46_Q1_2,VAR_RANG_46_Q1_2,VAR_MAX_46_Q1_2,VAR_AVG_46_Q1_2,VAR_SD_46_Q1_2,VAR_IQR_46_Q1_2,VAR_ACE_46_Q1_2,VAR_SDCE_46_Q1_2,VAR_IQRCE_46_Q1_2,VAR_CE3SD_46_Q1_2,VAR_TD_45_Q1_2,VAR_CE_45_Q1_2,VAR_MIN_45_Q1_2,VAR_MED_45_Q1_2,VAR_RANG_45_Q1_2,VAR_MAX_45_Q1_2,VAR_AVG_45_Q1_2,VAR_SD_45_Q1_2,VAR_IQR_45_Q1_2,VAR_ACE_45_Q1_2,VAR_SDCE_45_Q1_2,VAR_IQRCE_45_Q1_2,VAR_IDX_11_Q1_2,VAR_CE3SD_45_Q1_2,VAR_TD_1_Q2_2,VAR_CE_1_Q2_2,VAR_MIN_1_Q2_2,VAR_MED_1_Q2_2,VAR_RANG_1_Q2_2,VAR_MAX_1_Q2_2,VAR_AVG_1_Q2_2,VAR_SD_1_Q2_2,VAR_IQR_1_Q2_2,VAR_ACE_1_Q2_2,VAR_SDCE_1_Q2_2,VAR_IQRCE_1_Q2_2,VAR_CE3SD_1_Q2_2,VAR_TD_3_Q2_2,VAR_CE_3_Q2_2,VAR_MIN_3_Q2_2,VAR_MED_3_Q2_2,VAR_RANG_3_Q2_2,VAR_MAX_3_Q2_2,VAR_AVG_3_Q2_2,VAR_SD_3_Q2_2,VAR_IQR_3_Q2_2,VAR_ACE_3_Q2_2,VAR_SDCE_3_Q2_2,VAR_IQRCE_3_Q2_2,VAR_CE3SD_3_Q2_2,VAR_TD_5_Q2_2,VAR_CE_5_Q2_2,VAR_MIN_5_Q2_2,VAR_MED_5_Q2_2,VAR_RANG_5_Q2_2,VAR_MAX_5_Q2_2,VAR_AVG_5_Q2_2,VAR_SD_5_Q2_2,VAR_IQR_5_Q2_2,VAR_ACE_5_Q2_2,VAR_SDCE_5_Q2_2,VAR_IQRCE_5_Q2_2,VAR_CE3SD_5_Q2_2,VAR_TD_4_Q2_2,VAR_CE_4_Q2_2,VAR_MIN_4_Q2_2,VAR_MED_4_Q2_2,VAR_RANG_4_Q2_2,VAR_MAX_4_Q2_2,VAR_AVG_4_Q2_2,VAR_SD_4_Q2_2,VAR_IQR_4_Q2_2,VAR_ACE_4_Q2_2,VAR_SDCE_4_Q2_2,VAR_IQRCE_4_Q2_2,VAR_CE3SD_4_Q2_2,VAR_TD_12_Q2_2,VAR_CE_12_Q2_2,VAR_MIN_12_Q2_2,VAR_MED_12_Q2_2,VAR_RANG_12_Q2_2,VAR_MAX_12_Q2_2,VAR_AVG_12_Q2_2,VAR_SD_12_Q2_2,VAR_IQR_12_Q2_2,VAR_ACE_12_Q2_2,VAR_SDCE_12_Q2_2,VAR_IQRCE_12_Q2_2,VAR_CE3SD_12_Q2_2,VAR_TD_2_Q2_2,VAR_CE_2_Q2_2,VAR_MIN_2_Q2_2,VAR_MED_2_Q2_2,VAR_RANG_2_Q2_2,VAR_MAX_2_Q2_2,VAR_AVG_2_Q2_2,VAR_SD_2_Q2_2,VAR_IQR_2_Q2_2,VAR_ACE_2_Q2_2,VAR_SDCE_2_Q2_2,VAR_IQRCE_2_Q2_2,VAR_CE3SD_2_Q2_2,VAR_TD_46_Q2_2,VAR_CE_46_Q2_2,VAR_MIN_46_Q2_2,VAR_MED_46_Q2_2,VAR_RANG_46_Q2_2,VAR_MAX_46_Q2_2,VAR_AVG_46_Q2_2,VAR_SD_46_Q2_2,VAR_IQR_46_Q2_2,VAR_ACE_46_Q2_2,VAR_SDCE_46_Q2_2,VAR_IQRCE_46_Q2_2,VAR_CE3SD_46_Q2_2,VAR_TD_45_Q2_2,VAR_CE_45_Q2_2,VAR_MIN_45_Q2_2,VAR_MED_45_Q2_2,VAR_RANG_45_Q2_2,VAR_MAX_45_Q2_2,VAR_AVG_45_Q2_2,VAR_SD_45_Q2_2,VAR_IQR_45_Q2_2,VAR_ACE_45_Q2_2,VAR_SDCE_45_Q2_2,VAR_IQRCE_45_Q2_2,VAR_IDX_11_Q2_2,VAR_CE3SD_45_Q2_2,VAR_TD_1_Q3_2,VAR_CE_1_Q3_2,VAR_MIN_1_Q3_2,VAR_MED_1_Q3_2,VAR_RANG_1_Q3_2,VAR_MAX_1_Q3_2,VAR_AVG_1_Q3_2,VAR_SD_1_Q3_2,VAR_IQR_1_Q3_2,VAR_ACE_1_Q3_2,VAR_SDCE_1_Q3_2,VAR_IQRCE_1_Q3_2,VAR_CE3SD_1_Q3_2,VAR_TD_3_Q3_2,VAR_CE_3_Q3_2,VAR_MIN_3_Q3_2,VAR_MED_3_Q3_2,VAR_RANG_3_Q3_2,VAR_MAX_3_Q3_2,VAR_AVG_3_Q3_2,VAR_SD_3_Q3_2,VAR_IQR_3_Q3_2,VAR_ACE_3_Q3_2,VAR_SDCE_3_Q3_2,VAR_IQRCE_3_Q3_2,VAR_CE3SD_3_Q3_2,VAR_TD_5_Q3_2,VAR_CE_5_Q3_2,VAR_MIN_5_Q3_2,VAR_MED_5_Q3_2,VAR_RANG_5_Q3_2,VAR_MAX_5_Q3_2,VAR_AVG_5_Q3_2,VAR_SD_5_Q3_2,VAR_IQR_5_Q3_2,VAR_ACE_5_Q3_2,VAR_SDCE_5_Q3_2,VAR_IQRCE_5_Q3_2,VAR_CE3SD_5_Q3_2,VAR_TD_4_Q3_2,VAR_CE_4_Q3_2,VAR_MIN_4_Q3_2,VAR_MED_4_Q3_2,VAR_RANG_4_Q3_2,VAR_MAX_4_Q3_2,VAR_AVG_4_Q3_2,VAR_SD_4_Q3_2,VAR_IQR_4_Q3_2,VAR_ACE_4_Q3_2,VAR_SDCE_4_Q3_2,VAR_IQRCE_4_Q3_2,VAR_CE3SD_4_Q3_2,VAR_TD_12_Q3_2,VAR_CE_12_Q3_2,VAR_MIN_12_Q3_2,VAR_MED_12_Q3_2,VAR_RANG_12_Q3_2,VAR_MAX_12_Q3_2,VAR_AVG_12_Q3_2,VAR_SD_12_Q3_2,VAR_IQR_12_Q3_2,VAR_ACE_12_Q3_2,VAR_SDCE_12_Q3_2,VAR_IQRCE_12_Q3_2,VAR_CE3SD_12_Q3_2,VAR_TD_2_Q3_2,VAR_CE_2_Q3_2,VAR_MIN_2_Q3_2,VAR_MED_2_Q3_2,VAR_RANG_2_Q3_2,VAR_MAX_2_Q3_2,VAR_AVG_2_Q3_2,VAR_SD_2_Q3_2,VAR_IQR_2_Q3_2,VAR_ACE_2_Q3_2,VAR_SDCE_2_Q3_2,VAR_IQRCE_2_Q3_2,VAR_CE3SD_2_Q3_2,VAR_TD_46_Q3_2,VAR_CE_46_Q3_2,VAR_MIN_46_Q3_2,VAR_MED_46_Q3_2,VAR_RANG_46_Q3_2,VAR_MAX_46_Q3_2,VAR_AVG_46_Q3_2,VAR_SD_46_Q3_2,VAR_IQR_46_Q3_2,VAR_ACE_46_Q3_2,VAR_SDCE_46_Q3_2,VAR_IQRCE_46_Q3_2,VAR_CE3SD_46_Q3_2,VAR_TD_45_Q3_2,VAR_CE_45_Q3_2,VAR_MIN_45_Q3_2,VAR_MED_45_Q3_2,VAR_RANG_45_Q3_2,VAR_MAX_45_Q3_2,VAR_AVG_45_Q3_2,VAR_SD_45_Q3_2,VAR_IQR_45_Q3_2,VAR_ACE_45_Q3_2,VAR_SDCE_45_Q3_2,VAR_IQRCE_45_Q3_2,VAR_IDX_11_Q3_2,VAR_CE3SD_45_Q3_2,VAR_TD_1_Q4_2,VAR_CE_1_Q4_2,VAR_MIN_1_Q4_2,VAR_MED_1_Q4_2,VAR_RANG_1_Q4_2,VAR_MAX_1_Q4_2,VAR_AVG_1_Q4_2,VAR_SD_1_Q4_2,VAR_IQR_1_Q4_2,VAR_ACE_1_Q4_2,VAR_SDCE_1_Q4_2,VAR_IQRCE_1_Q4_2,VAR_CE3SD_1_Q4_2,VAR_TD_3_Q4_2,VAR_CE_3_Q4_2,VAR_MIN_3_Q4_2,VAR_MED_3_Q4_2,VAR_RANG_3_Q4_2,VAR_MAX_3_Q4_2,VAR_AVG_3_Q4_2,VAR_SD_3_Q4_2,VAR_IQR_3_Q4_2,VAR_ACE_3_Q4_2,VAR_SDCE_3_Q4_2,VAR_IQRCE_3_Q4_2,VAR_CE3SD_3_Q4_2,VAR_TD_5_Q4_2,VAR_CE_5_Q4_2,VAR_MIN_5_Q4_2,VAR_MED_5_Q4_2,VAR_RANG_5_Q4_2,VAR_MAX_5_Q4_2,VAR_AVG_5_Q4_2,VAR_SD_5_Q4_2,VAR_IQR_5_Q4_2,VAR_ACE_5_Q4_2,VAR_SDCE_5_Q4_2,VAR_IQRCE_5_Q4_2,VAR_CE3SD_5_Q4_2,VAR_TD_4_Q4_2,VAR_CE_4_Q4_2,VAR_MIN_4_Q4_2,VAR_MED_4_Q4_2,VAR_RANG_4_Q4_2,VAR_MAX_4_Q4_2,VAR_AVG_4_Q4_2,VAR_SD_4_Q4_2,VAR_IQR_4_Q4_2,VAR_ACE_4_Q4_2,VAR_SDCE_4_Q4_2,VAR_IQRCE_4_Q4_2,VAR_CE3SD_4_Q4_2,VAR_TD_12_Q4_2,VAR_CE_12_Q4_2,VAR_MIN_12_Q4_2,VAR_MED_12_Q4_2,VAR_RANG_12_Q4_2,VAR_MAX_12_Q4_2,VAR_AVG_12_Q4_2,VAR_SD_12_Q4_2,VAR_IQR_12_Q4_2,VAR_ACE_12_Q4_2,VAR_SDCE_12_Q4_2,VAR_IQRCE_12_Q4_2,VAR_CE3SD_12_Q4_2,VAR_TD_2_Q4_2,VAR_CE_2_Q4_2,VAR_MIN_2_Q4_2,VAR_MED_2_Q4_2,VAR_RANG_2_Q4_2,VAR_MAX_2_Q4_2,VAR_AVG_2_Q4_2,VAR_SD_2_Q4_2,VAR_IQR_2_Q4_2,VAR_ACE_2_Q4_2,VAR_SDCE_2_Q4_2,VAR_IQRCE_2_Q4_2,VAR_CE3SD_2_Q4_2,VAR_TD_46_Q4_2,VAR_CE_46_Q4_2,VAR_MIN_46_Q4_2,VAR_MED_46_Q4_2,VAR_RANG_46_Q4_2,VAR_MAX_46_Q4_2,VAR_AVG_46_Q4_2,VAR_SD_46_Q4_2,VAR_IQR_46_Q4_2,VAR_ACE_46_Q4_2,VAR_SDCE_46_Q4_2,VAR_IQRCE_46_Q4_2,VAR_CE3SD_46_Q4_2,VAR_TD_45_Q4_2,VAR_CE_45_Q4_2,VAR_MIN_45_Q4_2,VAR_MED_45_Q4_2,VAR_RANG_45_Q4_2,VAR_MAX_45_Q4_2,VAR_AVG_45_Q4_2,VAR_SD_45_Q4_2,VAR_IQR_45_Q4_2,VAR_ACE_45_Q4_2,VAR_SDCE_45_Q4_2,VAR_IQRCE_45_Q4_2,VAR_IDX_11_Q4_2,VAR_CE3SD_45_Q4_2,VAR_TD_1_Q5_2,VAR_CE_1_Q5_2,VAR_MIN_1_Q5_2,VAR_MED_1_Q5_2,VAR_RANG_1_Q5_2,VAR_MAX_1_Q5_2,VAR_AVG_1_Q5_2,VAR_SD_1_Q5_2,VAR_IQR_1_Q5_2,VAR_ACE_1_Q5_2,VAR_SDCE_1_Q5_2,VAR_IQRCE_1_Q5_2,VAR_CE3SD_1_Q5_2,VAR_TD_3_Q5_2,VAR_CE_3_Q5_2,VAR_MIN_3_Q5_2,VAR_MED_3_Q5_2,VAR_RANG_3_Q5_2,VAR_MAX_3_Q5_2,VAR_AVG_3_Q5_2,VAR_SD_3_Q5_2,VAR_IQR_3_Q5_2,VAR_ACE_3_Q5_2,VAR_SDCE_3_Q5_2,VAR_IQRCE_3_Q5_2,VAR_CE3SD_3_Q5_2,VAR_TD_5_Q5_2,VAR_CE_5_Q5_2,VAR_MIN_5_Q5_2,VAR_MED_5_Q5_2,VAR_RANG_5_Q5_2,VAR_MAX_5_Q5_2,VAR_AVG_5_Q5_2,VAR_SD_5_Q5_2,VAR_IQR_5_Q5_2,VAR_ACE_5_Q5_2,VAR_SDCE_5_Q5_2,VAR_IQRCE_5_Q5_2,VAR_CE3SD_5_Q5_2,VAR_TD_4_Q5_2,VAR_CE_4_Q5_2,VAR_MIN_4_Q5_2,VAR_MED_4_Q5_2,VAR_RANG_4_Q5_2,VAR_MAX_4_Q5_2,VAR_AVG_4_Q5_2,VAR_SD_4_Q5_2,VAR_IQR_4_Q5_2,VAR_ACE_4_Q5_2,VAR_SDCE_4_Q5_2,VAR_IQRCE_4_Q5_2,VAR_CE3SD_4_Q5_2,VAR_TD_12_Q5_2,VAR_CE_12_Q5_2,VAR_MIN_12_Q5_2,VAR_MED_12_Q5_2,VAR_RANG_12_Q5_2,VAR_MAX_12_Q5_2,VAR_AVG_12_Q5_2,VAR_SD_12_Q5_2,VAR_IQR_12_Q5_2,VAR_ACE_12_Q5_2,VAR_SDCE_12_Q5_2,VAR_IQRCE_12_Q5_2,VAR_CE3SD_12_Q5_2,VAR_TD_2_Q5_2,VAR_CE_2_Q5_2,VAR_MIN_2_Q5_2,VAR_MED_2_Q5_2,VAR_RANG_2_Q5_2,VAR_MAX_2_Q5_2,VAR_AVG_2_Q5_2,VAR_SD_2_Q5_2,VAR_IQR_2_Q5_2,VAR_ACE_2_Q5_2,VAR_SDCE_2_Q5_2,VAR_IQRCE_2_Q5_2,VAR_CE3SD_2_Q5_2,VAR_TD_46_Q5_2,VAR_CE_46_Q5_2,VAR_MIN_46_Q5_2,VAR_MED_46_Q5_2,VAR_RANG_46_Q5_2,VAR_MAX_46_Q5_2,VAR_AVG_46_Q5_2,VAR_SD_46_Q5_2,VAR_IQR_46_Q5_2,VAR_ACE_46_Q5_2,VAR_SDCE_46_Q5_2,VAR_IQRCE_46_Q5_2,VAR_CE3SD_46_Q5_2,VAR_TD_45_Q5_2,VAR_CE_45_Q5_2,VAR_MIN_45_Q5_2,VAR_MED_45_Q5_2,VAR_RANG_45_Q5_2,VAR_MAX_45_Q5_2,VAR_AVG_45_Q5_2,VAR_SD_45_Q5_2,VAR_IQR_45_Q5_2,VAR_ACE_45_Q5_2,VAR_SDCE_45_Q5_2,VAR_IQRCE_45_Q5_2,VAR_IDX_11_Q5_2,VAR_CE3SD_45_Q5_2,DER_BOO_1_LOW,DER_BOO_1_NORM,DER_BOO_1_HGH,DER_BOO_3_LOW,DER_BOO_3_NORM,DER_BOO_3_HGH,DER_BOO_5_LOW,DER_BOO_5_NORM,DER_BOO_5_HGH,DER_BOO_4_LOW,DER_BOO_4_NORM,DER_BOO_4_HGH,DER_BOO_12_LOW,DER_BOO_12_NORM,DER_BOO_12_HGH,DER_BOO_2_LOW,DER_BOO_2_NORM,DER_BOO_2_HGH,DER_BOO_46_LOW,DER_BOO_46_NORM,DER_BOO_46_HGH,DER_BOO_45_LOW,DER_BOO_45_NORM,DER_BOO_45_HGH,DER_TD_LABEL_Q1_2,DER_TD_LABEL_Q2_2,DER_TD_LABEL_Q3_2,DER_TD_LABEL_Q4_2,DER_TD_LABEL_Q5_2,DER_CE_47_Q4_2,DER_TD_47_Q4_2,DER_CE_48_Q1_2,DER_CE_48_Q2_2,DER_CE_48_Q3_2,DER_CE_48_Q4_2,DER_CE_48_Q5_2,DER_TD_48_Q1_2,DER_TD_48_Q2_2,DER_TD_48_Q3_2,DER_TD_48_Q4_2,DER_TD_48_Q5_2,DER_CE_2_Q4_2,DER_TD_2_Q4_2,DER_RTO_49_Q5_2,DER_RTO_50_Q5_2,DER_SHT_5_Q5_2,DER_MDM_5_Q5_2,DER_LNG_5_Q5_2,DER_SHT_4_Q5_2,DER_MDM_4_Q5_2,DER_LNG_4_Q5_2,DER_CE_51_Q5_2,DER_RTO_52_Q5_2,DER_PRO_53_Q5_2,DER_PRO_54_Q5_2,DER_PRO_55_Q5_2,DER_PRO_56_Q5_2,DER_PRO_57_Q5_2,DER_PRO_58_Q5_2,DER_PRO_59_Q5_2,DER_PRO_60_Q5_2,DER_PRO_61_Q5_2,DER_PRO_62_Q5_2,CREATEDATE,VAR1_TD_8_Q1_2,VAR2_TD_8_Q1_2,VAR3_TD_8_Q1_2,VAR4_TD_8_Q1_2,VAR1_TD_8_Q2_2,VAR2_TD_8_Q2_2,VAR3_TD_8_Q2_2,VAR4_TD_8_Q2_2,VAR1_TD_8_Q3_2,VAR2_TD_8_Q3_2,VAR3_TD_8_Q3_2,VAR4_TD_8_Q3_2,VAR1_TD_8_Q4_2,VAR2_TD_8_Q4_2,VAR3_TD_8_Q4_2,VAR4_TD_8_Q4_2,VAR1_TD_8_Q5_2,VAR2_TD_8_Q5_2,VAR3_TD_8_Q5_2,VAR4_TD_8_Q5_2,DER_CE_63_Q5,VAR5_TD_8_Q1_6,VAR5_TD_8_Q2_6,VAR5_TD_8_Q3_6,VAR5_TD_8_Q4_6,VAR5_TD_8_Q5_6,IS_WEEKEND,CONSECUTIVE_RUNNING,CONSECUTIVE_SLEEP,sitename,BCS_SCORE-bcs_recorded_date,BCS_SCORE-body_condition_score,BODY_WEIGHTS-weight_recorded_date,BODY_WEIGHTS-entered_weight_lb,DEMOGRAPHICS-gender,DEMOGRAPHICS-date_of_birth,DEMOGRAPHICS-randomization_date_time,DEMOGRAPHICS-enroll_dog,DEMOGRAPHICS-d0_expected_date,DEMOGRAPHICS-latest_d0_avail_date,DEMOGRAPHICS-day0_date,DEMOGRAPHICS-day0_age,OWNER_DAILY_DAIRY - total_amount_time_walked,MEDICATION - medication,BODY_WEIGHTS-DAY0_BODY_WEIGHT,BCS_SCORE-DAY0_body_condition_score,clinical_itt,clinical_pp,questionnaire_itt_extract,walking_900,running_900,active_900,walking_300,running_300,active_300,walking_60,running_60,active_60,longest_running_event,longest_walking_event,active_periods_count_rolling,most_common_hour_rolling,active_periods_count_fixed,most_common_hour_fixed,patient_id,dog_and_owner_name,study_food,weight,mixed_breed,intact,sex,date_of_birth,baseline_mean_soft_stiction,treatment_mean_soft_stiction,IS_QUALIFIED_NEW,Qualifying_Data_Day_NEW,NORMALIZED_QUALIFYING_STUDY_DAY_NEW
0,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,10-09-2019,-30,NaN,22.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,NaN,NO,Duration less than 20 hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.50,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.25,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,0.000000,0.00,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.50,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.25,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,0.000000,0.00,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.50,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.25,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,0.000000,0.00,100.0,NaN,205.0,6.0,3.0,20.0,3-103,103.0,34.166667,37.865111,34.25,1.50,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.0,0.00,0.000000,0.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.0,0.00,0.000000,0.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.0,0.00,0.000000,0.00,0.0,45.0,5.0,2.0,5.0,Feb-24,24.0,9.000000,8.888194,6.0,1.25,0.000000,0.0,0.0,8125.0,2.0,518.0,4062.5,518-7607,7607.0,4062.5,5012.679972,3544.5,0.5,0.000000,0.0,0.0,256.0,1.0,256.0,256.0,256-256,256.0,256.000000,0.000000,0.0,0.25,0.000000,0.00,100.0,1.0,205,6,3,20.0,3-103,103,34.166667,37.865111,34.25,1.50,0.000000,0.0,0.0,0,0,0,0.0,NaN,0,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.0,0,0,0,0.0,NaN,0,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.0,0,0,0,0.0,NaN,0,0.000000,0.000000,0.0,0.00,0.000000,0.00,0.0,0,0,0,0.0,NaN,0,0.000000,0.000000,0.0,0.00,0.000000,0.00,0.0,45,5,2,5.0,Feb-24,24,9.000000,8.888194,6.0,1.25,0.000000,0.0,0.0,8125,2,518,4062.5,518-7607,7607,4062.500000,5012.679972,3544.5,0.5,0.000000,0.0,0.0,256,1,256,256.0,256-256,256,256.000000,0.000000,0.00,0.25,0.000000,0.00,100.0,1.0,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,0,0,0,250,250,NaN,NaN,NaN,NaN,3.0,NaN,3.0,NaN,NaN,143.0,NaN,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.18,0.82,0.00,0.0,0.0,0.18,0.82,0.00,0.0,0.0,19:41.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,Quakertown,NaN,NaN,NaN,NaN,Neutered Male,03-07-2014,NaN,Yes,10-10-2019,07-11-2019,10-10-2019,5.0,NaN,NaN,NaN,NaN,True,True,True,0,0,0,0,0,0,0,0,0,NaN,0 days 00:00:24,0.0,NaN,0.0,NaN,EPRO-QT-02,Bandit Hocking,Peach,62.8,True,False,Male,03-07-2014 00:00,0.0,0.0,NO,NaN,NaN
1,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,11-09-2019,-29,NaN,23.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,NaN,NO,Duration less than 20 hours,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.00,145.50,42.003968,38.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.00000,0.000000,0.0,7.00,6.658328,6.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,5.25,4.358899,4.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.00000,0.0,2.00,2.081666,2.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.0,7.75,2.309401,2.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,0.000000,0.0,143.25,33.867388,32.5,0.0,21596.0,6949.0,1.0,2.0,1-11012,11012.0,3.107785,132.083349,1.0,3025.5,1269.256672,897.5,1.0,0.0,0.0,0.0,0.0,0-0,0.0,0.0,0.0,0.0,3.50,1.154701,1.00,88.0,0.0,6465.0,146.0,1.0,13.5,1-478,478.0,44.280822,82.490772,28.5,145.50,42.003968,38.0,6.0,39.0,17.0,1.0,1.0,01-Sep,9.0,2.294118,2.443479,1.00,7.00,6.658328,6.00,2.0,5.0,5.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,5.25,4.358899,4.00,5.0,5.0,5.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,2.00,2.081666,2.00,5.0,6035.0,8.0,2.0,811.5,2-1636,1636.0,754.375000,633.587729,1099.0,7.75,2.309401,2.00,0.0,1164.0,153.0,1.0,5.0,Jan-53,53.0,7.607843,8.123419,8.00,143.25,33.867388,32.5,6.0,7874.0,5154.0,1.0,2.0,01-Feb,2.0,1.527745,0.499278,1.0,3025.5,1269.256672,897.5,2720.0,13.0,4.0,1.0,2.0,01-Oct,10.0,5.000000,5.196152,4.5,3.50,1.154701,1.00,88.0,1.0,9312.0,222.0,1.0,21.0,1-350,350.0,41.945946,55.484348,36.75,145.50,42.003968,38.0,7.0,6.0,5.0,1.0,1.0,01-Feb,2.0,1.200000,0.447214,0.00,7.00,6.658328,6.00,1.0,24.0,12.0,1.0,1.0,01-Jul,7.0,2.000000,1.758098,1.25,5.25,4.358899,4.00,1.0,2.0,2.0,1.0,1.0,01-Jan,1.0,1.0,0.0,0.0,2.00,2.081666,2.00,2.0,10601.0,12.0,6.0,456.0,Jun-65,2865.0,883.416667,970.777426,728.00,7.75,2.309401,2.00,0.0,1630.0,218.0,1.0,4.0,Jan-85,85.0,7.477064,9.998245,8.75,143.25,33.867388,32.5,8.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,3025.5,1269.256672,897.5,0.0,25.0,6.0,1.0,11.5,Jan-20,20.0,11.500000,13.435029,9.5,3.50,1.154701,1.00,88.0,4.0,9646.0,215.0,1.0,15.0,1-572,572.0,44.865116,74.280760,37.50,145.50,42.003968,38.0,8.0,12.0,6.0,1.0,1.0,01-Jul,7.0,2.000000,2.449490,0.0,7.00,6.658328,6.00,0.0,11.0,4.0,1.0,2.5,01-May,5.0,2.750000,2.061553,3.25,5.25,4.358899,4.00,0.0,1.0,1.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,2.00,2.081666,2.00,1.0,9277.0,12.0,86.0,479.0,86-3232,3232.0,773.083333,863.856939,544.5,7.75,2.309401,2.00,1.0,1397.0,202.0,1.0,3.0,Jan-60,60.0,6.915842,8.306794,8.0,143.25,33.867388,32.5,8.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.000000,0.0,3025.5,1269.256672,897.5,0.0,1256.0,4.0,1.0,1254.0,1-1253,1253.0,1254.000000,0.000000,0.0,3.50,1.154701,1.00,88.0,4.0,25423,582,1,16.0,1-572,572,43.682131,70.728033,34.75,145.50,42.003968,38.0,23.0,57,28,1,1.0,01-Sep,9,2.035714,2.202392,1.00,7.00,6.658328,6.00,3.0,40,21,1,1.0,01-Jul,7,1.904762,1.640267,1.00,5.25,4.358899,4.00,2.0,8,8,1,1.0,01-Jan,1,1.000000,0.000000,0.0,2.00,2.081666,2.00,8.0,25913,31,2,524.0,Feb-32,3232,835.903226,847.784892,973.5,7.75,2.309401,2.00,3.0,4191,573,1,4.0,Jan-85,85,7.314136,8.932875,8.0,143.25,33.867388,32.5,24.0,29470,12102,1,2.0,1-11012,11012,2.435135,100.088199,1.0,3025.5,1269.256672,897.5,1.0,1294,14,1,11.5,1-1253,1253,320.650000,625.743781,327.25,3.50,1.154701,1.00,88.0,1.0,False,False,True,False,True,False,True,False,False,True,False,False,False,False,True,False,False,True,False,False,True,False,False,True,0,13713,21575,20344,55632,NaN,NaN,62.0,125.0,99.0,NaN,286.0,4771.0,7305.0,6386.0,NaN,18673.0,NaN,NaN,NaN,NaN,14.0,6.0,1.0,8.0,0.0,0.0,1.0,0.87,0.08,0.46,0.00,0.0,0.0,0.14,0.86,0.00,0.0,0.0,19:41.3,0.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN,NaN,NaN,0,0,0,Quakertown,NaN,NaN,NaN,NaN,Neutered Male,03-07-2014,NaN,Yes,10-10-2019,07-11-2019,10-10-2019,5.0,NaN,NaN,NaN,NaN,True,True,True,1,0,1,0,0,0,1,0,1,0 days 00:00:09,0 days 00:01:25,1.0,17.0,1.0,17.0,EPRO-QT-02,Bandit Hocking,Peach,62.8,True,False,Male,03-07-2014 00:00,0.0,0.0,NO,NaN,NaN

In [4]:
data_additional_metric['study_food'].value_counts()

Peach    6687
Black    6151
None     1132
Name: study_food, dtype: int64

In [5]:
population.head()

,PET_ID,wearables_itt,wearables_pp,wearables_itt_extract,wearables_pp_extract,itt_failure_reason,pp_failure_reason
0,3347,True,True,True,True,NaN,NaN
1,3348,True,False,True,False,NaN,Subject not in Clinical PP; Major deviation or...
2,3349,True,False,True,False,NaN,Subject not in Clinical PP; Major deviation or...
3,3350,True,True,True,True,NaN,NaN
4,3391,True,False,True,False,NaN,Subject not in Clinical PP; Major deviation or...

In [3]:
data_merged = pd.merge(data_additional_metric, population, on=['PET_ID'], how='left')

In [4]:
# Filter dataset for subgroup analysis
data = data_merged[(data_merged["wearables_itt"] == True) & (data_merged['study_food'].isin(['Peach', 'Black']))]

In [5]:
data = data[data['NORMALIZED_QUALIFYING_STUDY_DAY_NEW'] < 0]

In [7]:
data1  = data[data['IS_QUALIFIED_NEW'] == 'YES']

In [8]:
data1.shape

(3033, 693)

In [6]:
data.shape

(3033, 693)

In [10]:
data.head()

,PET_ID,EXTERNAL_ID,DEVICE_ID,STUDY_ID,STUDY_NAME,PET_NAME,DATE,NORMALIZED_STUDY_DAY,NORMALIZED_QUALIFYING_STUDY_DAY,STUDY_DAY_COUNTER,STUDY_GROUP,BASELINE_START,START_DATE,ENROLLMENT_DATE,COMPLETION_DATE,END_DATE,EXCESSIVE_RUNNING,TIMEZONE,QUALIFYING_DATA_DAY,IS_QUALIFIED,DAILYDATAQUALITYINDREASON,VAR_TD_1_Q1_2,VAR_CE_1_Q1_2,VAR_MIN_1_Q1_2,VAR_MED_1_Q1_2,VAR_RANG_1_Q1_2,VAR_MAX_1_Q1_2,VAR_AVG_1_Q1_2,VAR_SD_1_Q1_2,VAR_IQR_1_Q1_2,VAR_ACE_1_Q1_2,VAR_SDCE_1_Q1_2,VAR_IQRCE_1_Q1_2,VAR_CE3SD_1_Q1_2,VAR_TD_3_Q1_2,VAR_CE_3_Q1_2,VAR_MIN_3_Q1_2,VAR_MED_3_Q1_2,VAR_RANG_3_Q1_2,VAR_MAX_3_Q1_2,VAR_AVG_3_Q1_2,VAR_SD_3_Q1_2,VAR_IQR_3_Q1_2,VAR_ACE_3_Q1_2,VAR_SDCE_3_Q1_2,VAR_IQRCE_3_Q1_2,VAR_CE3SD_3_Q1_2,VAR_TD_5_Q1_2,VAR_CE_5_Q1_2,VAR_MIN_5_Q1_2,VAR_MED_5_Q1_2,VAR_RANG_5_Q1_2,VAR_MAX_5_Q1_2,VAR_AVG_5_Q1_2,VAR_SD_5_Q1_2,VAR_IQR_5_Q1_2,VAR_ACE_5_Q1_2,VAR_SDCE_5_Q1_2,VAR_IQRCE_5_Q1_2,VAR_CE3SD_5_Q1_2,VAR_TD_4_Q1_2,VAR_CE_4_Q1_2,VAR_MIN_4_Q1_2,VAR_MED_4_Q1_2,VAR_RANG_4_Q1_2,VAR_MAX_4_Q1_2,VAR_AVG_4_Q1_2,VAR_SD_4_Q1_2,VAR_IQR_4_Q1_2,VAR_ACE_4_Q1_2,VAR_SDCE_4_Q1_2,VAR_IQRCE_4_Q1_2,VAR_CE3SD_4_Q1_2,VAR_TD_12_Q1_2,VAR_CE_12_Q1_2,VAR_MIN_12_Q1_2,VAR_MED_12_Q1_2,VAR_RANG_12_Q1_2,VAR_MAX_12_Q1_2,VAR_AVG_12_Q1_2,VAR_SD_12_Q1_2,VAR_IQR_12_Q1_2,VAR_ACE_12_Q1_2,VAR_SDCE_12_Q1_2,VAR_IQRCE_12_Q1_2,VAR_CE3SD_12_Q1_2,VAR_TD_2_Q1_2,VAR_CE_2_Q1_2,VAR_MIN_2_Q1_2,VAR_MED_2_Q1_2,VAR_RANG_2_Q1_2,VAR_MAX_2_Q1_2,VAR_AVG_2_Q1_2,VAR_SD_2_Q1_2,VAR_IQR_2_Q1_2,VAR_ACE_2_Q1_2,VAR_SDCE_2_Q1_2,VAR_IQRCE_2_Q1_2,VAR_CE3SD_2_Q1_2,VAR_TD_46_Q1_2,VAR_CE_46_Q1_2,VAR_MIN_46_Q1_2,VAR_MED_46_Q1_2,VAR_RANG_46_Q1_2,VAR_MAX_46_Q1_2,VAR_AVG_46_Q1_2,VAR_SD_46_Q1_2,VAR_IQR_46_Q1_2,VAR_ACE_46_Q1_2,VAR_SDCE_46_Q1_2,VAR_IQRCE_46_Q1_2,VAR_CE3SD_46_Q1_2,VAR_TD_45_Q1_2,VAR_CE_45_Q1_2,VAR_MIN_45_Q1_2,VAR_MED_45_Q1_2,VAR_RANG_45_Q1_2,VAR_MAX_45_Q1_2,VAR_AVG_45_Q1_2,VAR_SD_45_Q1_2,VAR_IQR_45_Q1_2,VAR_ACE_45_Q1_2,VAR_SDCE_45_Q1_2,VAR_IQRCE_45_Q1_2,VAR_IDX_11_Q1_2,VAR_CE3SD_45_Q1_2,VAR_TD_1_Q2_2,VAR_CE_1_Q2_2,VAR_MIN_1_Q2_2,VAR_MED_1_Q2_2,VAR_RANG_1_Q2_2,VAR_MAX_1_Q2_2,VAR_AVG_1_Q2_2,VAR_SD_1_Q2_2,VAR_IQR_1_Q2_2,VAR_ACE_1_Q2_2,VAR_SDCE_1_Q2_2,VAR_IQRCE_1_Q2_2,VAR_CE3SD_1_Q2_2,VAR_TD_3_Q2_2,VAR_CE_3_Q2_2,VAR_MIN_3_Q2_2,VAR_MED_3_Q2_2,VAR_RANG_3_Q2_2,VAR_MAX_3_Q2_2,VAR_AVG_3_Q2_2,VAR_SD_3_Q2_2,VAR_IQR_3_Q2_2,VAR_ACE_3_Q2_2,VAR_SDCE_3_Q2_2,VAR_IQRCE_3_Q2_2,VAR_CE3SD_3_Q2_2,VAR_TD_5_Q2_2,VAR_CE_5_Q2_2,VAR_MIN_5_Q2_2,VAR_MED_5_Q2_2,VAR_RANG_5_Q2_2,VAR_MAX_5_Q2_2,VAR_AVG_5_Q2_2,VAR_SD_5_Q2_2,VAR_IQR_5_Q2_2,VAR_ACE_5_Q2_2,VAR_SDCE_5_Q2_2,VAR_IQRCE_5_Q2_2,VAR_CE3SD_5_Q2_2,VAR_TD_4_Q2_2,VAR_CE_4_Q2_2,VAR_MIN_4_Q2_2,VAR_MED_4_Q2_2,VAR_RANG_4_Q2_2,VAR_MAX_4_Q2_2,VAR_AVG_4_Q2_2,VAR_SD_4_Q2_2,VAR_IQR_4_Q2_2,VAR_ACE_4_Q2_2,VAR_SDCE_4_Q2_2,VAR_IQRCE_4_Q2_2,VAR_CE3SD_4_Q2_2,VAR_TD_12_Q2_2,VAR_CE_12_Q2_2,VAR_MIN_12_Q2_2,VAR_MED_12_Q2_2,VAR_RANG_12_Q2_2,VAR_MAX_12_Q2_2,VAR_AVG_12_Q2_2,VAR_SD_12_Q2_2,VAR_IQR_12_Q2_2,VAR_ACE_12_Q2_2,VAR_SDCE_12_Q2_2,VAR_IQRCE_12_Q2_2,VAR_CE3SD_12_Q2_2,VAR_TD_2_Q2_2,VAR_CE_2_Q2_2,VAR_MIN_2_Q2_2,VAR_MED_2_Q2_2,VAR_RANG_2_Q2_2,VAR_MAX_2_Q2_2,VAR_AVG_2_Q2_2,VAR_SD_2_Q2_2,VAR_IQR_2_Q2_2,VAR_ACE_2_Q2_2,VAR_SDCE_2_Q2_2,VAR_IQRCE_2_Q2_2,VAR_CE3SD_2_Q2_2,VAR_TD_46_Q2_2,VAR_CE_46_Q2_2,VAR_MIN_46_Q2_2,VAR_MED_46_Q2_2,VAR_RANG_46_Q2_2,VAR_MAX_46_Q2_2,VAR_AVG_46_Q2_2,VAR_SD_46_Q2_2,VAR_IQR_46_Q2_2,VAR_ACE_46_Q2_2,VAR_SDCE_46_Q2_2,VAR_IQRCE_46_Q2_2,VAR_CE3SD_46_Q2_2,VAR_TD_45_Q2_2,VAR_CE_45_Q2_2,VAR_MIN_45_Q2_2,VAR_MED_45_Q2_2,VAR_RANG_45_Q2_2,VAR_MAX_45_Q2_2,VAR_AVG_45_Q2_2,VAR_SD_45_Q2_2,VAR_IQR_45_Q2_2,VAR_ACE_45_Q2_2,VAR_SDCE_45_Q2_2,VAR_IQRCE_45_Q2_2,VAR_IDX_11_Q2_2,VAR_CE3SD_45_Q2_2,VAR_TD_1_Q3_2,VAR_CE_1_Q3_2,VAR_MIN_1_Q3_2,VAR_MED_1_Q3_2,VAR_RANG_1_Q3_2,VAR_MAX_1_Q3_2,VAR_AVG_1_Q3_2,VAR_SD_1_Q3_2,VAR_IQR_1_Q3_2,VAR_ACE_1_Q3_2,VAR_SDCE_1_Q3_2,VAR_IQRCE_1_Q3_2,VAR_CE3SD_1_Q3_2,VAR_TD_3_Q3_2,VAR_CE_3_Q3_2,VAR_MIN_3_Q3_2,VAR_MED_3_Q3_2,VAR_RANG_3_Q3_2,VAR_MAX_3_Q3_2,VAR_AVG_3_Q3_2,VAR_SD_3_Q3_2,VAR_IQR_3_Q3_2,VAR_ACE_3_Q3_2,VAR_SDCE_3_Q3_2,VAR_IQRCE_3_Q3_2,VAR_CE3SD_3_Q3_2,VAR_TD_5_Q3_2,VAR_CE_5_Q3_2,VAR_MIN_5_Q3_2,VAR_MED_5_Q3_2,VAR_RANG_5_Q3_2,VAR_MAX_5_Q3_2,VAR_AVG_5_Q3_2,VAR_SD_5_Q3_2,VAR_IQR_5_Q3_2,VAR_ACE_5_Q3_2,VAR_SDCE_5_Q3_2,VAR_IQRCE_5_Q3_2,VAR_CE3SD_5_Q3_2,VAR_TD_4_Q3_2,VAR_CE_4_Q3_2,VAR_MIN_4_Q3_2,VAR_MED_4_Q3_2,VAR_RANG_4_Q3_2,VAR_MAX_4_Q3_2,VAR_AVG_4_Q3_2,VAR_SD_4_Q3_2,VAR_IQR_4_Q3_2,VAR_ACE_4_Q3_2,VAR_SDCE_4_Q3_2,VAR_IQRCE_4_Q3_2,VAR_CE3SD_4_Q3_2,VAR_TD_12_Q3_2,VAR_CE_12_Q3_2,VAR_MIN_12_Q3_2,VAR_MED_12_Q3_2,VAR_RANG_12_Q3_2,VAR_MAX_12_Q3_2,VAR_AVG_12_Q3_2,VAR_SD_12_Q3_2,VAR_IQR_12_Q3_2,VAR_ACE_12_Q3_2,VAR_SDCE_12_Q3_2,VAR_IQRCE_12_Q3_2,VAR_CE3SD_12_Q3_2,VAR_TD_2_Q3_2,VAR_CE_2_Q3_2,VAR_MIN_2_Q3_2,VAR_MED_2_Q3_2,VAR_RANG_2_Q3_2,VAR_MAX_2_Q3_2,VAR_AVG_2_Q3_2,VAR_SD_2_Q3_2,VAR_IQR_2_Q3_2,VAR_ACE_2_Q3_2,VAR_SDCE_2_Q3_2,VAR_IQRCE_2_Q3_2,VAR_CE3SD_2_Q3_2,VAR_TD_46_Q3_2,VAR_CE_46_Q3_2,VAR_MIN_46_Q3_2,VAR_MED_46_Q3_2,VAR_RANG_46_Q3_2,VAR_MAX_46_Q3_2,VAR_AVG_46_Q3_2,VAR_SD_46_Q3_2,VAR_IQR_46_Q3_2,VAR_ACE_46_Q3_2,VAR_SDCE_46_Q3_2,VAR_IQRCE_46_Q3_2,VAR_CE3SD_46_Q3_2,VAR_TD_45_Q3_2,VAR_CE_45_Q3_2,VAR_MIN_45_Q3_2,VAR_MED_45_Q3_2,VAR_RANG_45_Q3_2,VAR_MAX_45_Q3_2,VAR_AVG_45_Q3_2,VAR_SD_45_Q3_2,VAR_IQR_45_Q3_2,VAR_ACE_45_Q3_2,VAR_SDCE_45_Q3_2,VAR_IQRCE_45_Q3_2,VAR_IDX_11_Q3_2,VAR_CE3SD_45_Q3_2,VAR_TD_1_Q4_2,VAR_CE_1_Q4_2,VAR_MIN_1_Q4_2,VAR_MED_1_Q4_2,VAR_RANG_1_Q4_2,VAR_MAX_1_Q4_2,VAR_AVG_1_Q4_2,VAR_SD_1_Q4_2,VAR_IQR_1_Q4_2,VAR_ACE_1_Q4_2,VAR_SDCE_1_Q4_2,VAR_IQRCE_1_Q4_2,VAR_CE3SD_1_Q4_2,VAR_TD_3_Q4_2,VAR_CE_3_Q4_2,VAR_MIN_3_Q4_2,VAR_MED_3_Q4_2,VAR_RANG_3_Q4_2,VAR_MAX_3_Q4_2,VAR_AVG_3_Q4_2,VAR_SD_3_Q4_2,VAR_IQR_3_Q4_2,VAR_ACE_3_Q4_2,VAR_SDCE_3_Q4_2,VAR_IQRCE_3_Q4_2,VAR_CE3SD_3_Q4_2,VAR_TD_5_Q4_2,VAR_CE_5_Q4_2,VAR_MIN_5_Q4_2,VAR_MED_5_Q4_2,VAR_RANG_5_Q4_2,VAR_MAX_5_Q4_2,VAR_AVG_5_Q4_2,VAR_SD_5_Q4_2,VAR_IQR_5_Q4_2,VAR_ACE_5_Q4_2,VAR_SDCE_5_Q4_2,VAR_IQRCE_5_Q4_2,VAR_CE3SD_5_Q4_2,VAR_TD_4_Q4_2,VAR_CE_4_Q4_2,VAR_MIN_4_Q4_2,VAR_MED_4_Q4_2,VAR_RANG_4_Q4_2,VAR_MAX_4_Q4_2,VAR_AVG_4_Q4_2,VAR_SD_4_Q4_2,VAR_IQR_4_Q4_2,VAR_ACE_4_Q4_2,VAR_SDCE_4_Q4_2,VAR_IQRCE_4_Q4_2,VAR_CE3SD_4_Q4_2,VAR_TD_12_Q4_2,VAR_CE_12_Q4_2,VAR_MIN_12_Q4_2,VAR_MED_12_Q4_2,VAR_RANG_12_Q4_2,VAR_MAX_12_Q4_2,VAR_AVG_12_Q4_2,VAR_SD_12_Q4_2,VAR_IQR_12_Q4_2,VAR_ACE_12_Q4_2,VAR_SDCE_12_Q4_2,VAR_IQRCE_12_Q4_2,VAR_CE3SD_12_Q4_2,VAR_TD_2_Q4_2,VAR_CE_2_Q4_2,VAR_MIN_2_Q4_2,VAR_MED_2_Q4_2,VAR_RANG_2_Q4_2,VAR_MAX_2_Q4_2,VAR_AVG_2_Q4_2,VAR_SD_2_Q4_2,VAR_IQR_2_Q4_2,VAR_ACE_2_Q4_2,VAR_SDCE_2_Q4_2,VAR_IQRCE_2_Q4_2,VAR_CE3SD_2_Q4_2,VAR_TD_46_Q4_2,VAR_CE_46_Q4_2,VAR_MIN_46_Q4_2,VAR_MED_46_Q4_2,VAR_RANG_46_Q4_2,VAR_MAX_46_Q4_2,VAR_AVG_46_Q4_2,VAR_SD_46_Q4_2,VAR_IQR_46_Q4_2,VAR_ACE_46_Q4_2,VAR_SDCE_46_Q4_2,VAR_IQRCE_46_Q4_2,VAR_CE3SD_46_Q4_2,VAR_TD_45_Q4_2,VAR_CE_45_Q4_2,VAR_MIN_45_Q4_2,VAR_MED_45_Q4_2,VAR_RANG_45_Q4_2,VAR_MAX_45_Q4_2,VAR_AVG_45_Q4_2,VAR_SD_45_Q4_2,VAR_IQR_45_Q4_2,VAR_ACE_45_Q4_2,VAR_SDCE_45_Q4_2,VAR_IQRCE_45_Q4_2,VAR_IDX_11_Q4_2,VAR_CE3SD_45_Q4_2,VAR_TD_1_Q5_2,VAR_CE_1_Q5_2,VAR_MIN_1_Q5_2,VAR_MED_1_Q5_2,VAR_RANG_1_Q5_2,VAR_MAX_1_Q5_2,VAR_AVG_1_Q5_2,VAR_SD_1_Q5_2,VAR_IQR_1_Q5_2,VAR_ACE_1_Q5_2,VAR_SDCE_1_Q5_2,VAR_IQRCE_1_Q5_2,VAR_CE3SD_1_Q5_2,VAR_TD_3_Q5_2,VAR_CE_3_Q5_2,VAR_MIN_3_Q5_2,VAR_MED_3_Q5_2,VAR_RANG_3_Q5_2,VAR_MAX_3_Q5_2,VAR_AVG_3_Q5_2,VAR_SD_3_Q5_2,VAR_IQR_3_Q5_2,VAR_ACE_3_Q5_2,VAR_SDCE_3_Q5_2,VAR_IQRCE_3_Q5_2,VAR_CE3SD_3_Q5_2,VAR_TD_5_Q5_2,VAR_CE_5_Q5_2,VAR_MIN_5_Q5_2,VAR_MED_5_Q5_2,VAR_RANG_5_Q5_2,VAR_MAX_5_Q5_2,VAR_AVG_5_Q5_2,VAR_SD_5_Q5_2,VAR_IQR_5_Q5_2,VAR_ACE_5_Q5_2,VAR_SDCE_5_Q5_2,VAR_IQRCE_5_Q5_2,VAR_CE3SD_5_Q5_2,VAR_TD_4_Q5_2,VAR_CE_4_Q5_2,VAR_MIN_4_Q5_2,VAR_MED_4_Q5_2,VAR_RANG_4_Q5_2,VAR_MAX_4_Q5_2,VAR_AVG_4_Q5_2,VAR_SD_4_Q5_2,VAR_IQR_4_Q5_2,VAR_ACE_4_Q5_2,VAR_SDCE_4_Q5_2,VAR_IQRCE_4_Q5_2,VAR_CE3SD_4_Q5_2,VAR_TD_12_Q5_2,VAR_CE_12_Q5_2,VAR_MIN_12_Q5_2,VAR_MED_12_Q5_2,VAR_RANG_12_Q5_2,VAR_MAX_12_Q5_2,VAR_AVG_12_Q5_2,VAR_SD_12_Q5_2,VAR_IQR_12_Q5_2,VAR_ACE_12_Q5_2,VAR_SDCE_12_Q5_2,VAR_IQRCE_12_Q5_2,VAR_CE3SD_12_Q5_2,VAR_TD_2_Q5_2,VAR_CE_2_Q5_2,VAR_MIN_2_Q5_2,VAR_MED_2_Q5_2,VAR_RANG_2_Q5_2,VAR_MAX_2_Q5_2,VAR_AVG_2_Q5_2,VAR_SD_2_Q5_2,VAR_IQR_2_Q5_2,VAR_ACE_2_Q5_2,VAR_SDCE_2_Q5_2,VAR_IQRCE_2_Q5_2,VAR_CE3SD_2_Q5_2,VAR_TD_46_Q5_2,VAR_CE_46_Q5_2,VAR_MIN_46_Q5_2,VAR_MED_46_Q5_2,VAR_RANG_46_Q5_2,VAR_MAX_46_Q5_2,VAR_AVG_46_Q5_2,VAR_SD_46_Q5_2,VAR_IQR_46_Q5_2,VAR_ACE_46_Q5_2,VAR_SDCE_46_Q5_2,VAR_IQRCE_46_Q5_2,VAR_CE3SD_46_Q5_2,VAR_TD_45_Q5_2,VAR_CE_45_Q5_2,VAR_MIN_45_Q5_2,VAR_MED_45_Q5_2,VAR_RANG_45_Q5_2,VAR_MAX_45_Q5_2,VAR_AVG_45_Q5_2,VAR_SD_45_Q5_2,VAR_IQR_45_Q5_2,VAR_ACE_45_Q5_2,VAR_SDCE_45_Q5_2,VAR_IQRCE_45_Q5_2,VAR_IDX_11_Q5_2,VAR_CE3SD_45_Q5_2,DER_BOO_1_LOW,DER_BOO_1_NORM,DER_BOO_1_HGH,DER_BOO_3_LOW,DER_BOO_3_NORM,DER_BOO_3_HGH,DER_BOO_5_LOW,DER_BOO_5_NORM,DER_BOO_5_HGH,DER_BOO_4_LOW,DER_BOO_4_NORM,DER_BOO_4_HGH,DER_BOO_12_LOW,DER_BOO_12_NORM,DER_BOO_12_HGH,DER_BOO_2_LOW,DER_BOO_2_NORM,DER_BOO_2_HGH,DER_BOO_46_LOW,DER_BOO_46_NORM,DER_BOO_46_HGH,DER_BOO_45_LOW,DER_BOO_45_NORM,DER_BOO_45_HGH,DER_TD_LABEL_Q1_2,DER_TD_LABEL_Q2_2,DER_TD_LABEL_Q3_2,DER_TD_LABEL_Q4_2,DER_TD_LABEL_Q5_2,DER_CE_47_Q4_2,DER_TD_47_Q4_2,DER_CE_48_Q1_2,DER_CE_48_Q2_2,DER_CE_48_Q3_2,DER_CE_48_Q4_2,DER_CE_48_Q5_2,DER_TD_48_Q1_2,DER_TD_48_Q2_2,DER_TD_48_Q3_2,DER_TD_48_Q4_2,DER_TD_48_Q5_2,DER_CE_2_Q4_2,DER_TD_2_Q4_2,DER_RTO_49_Q5_2,DER_RTO_50_Q5_2,DER_SHT_5_Q5_2,DER_MDM_5_Q5_2,DER_LNG_5_Q5_2,DER_SHT_4_Q5_2,DER_MDM_4_Q5_2,DER_LNG_4_Q5_2,DER_CE_51_Q5_2,DER_RTO_52_Q5_2,DER_PRO_53_Q5_2,DER_PRO_54_Q5_2,DER_PRO_55_Q5_2,DER_PRO_56_Q5_2,DER_PRO_57_Q5_2,DER_PRO_58_Q5_2,DER_PRO_59_Q5_2,DER_PRO_60_Q5_2,DER_PRO_61_Q5_2,DER_PRO_62_Q5_2,CREATEDATE,VAR1_TD_8_Q1_2,VAR2_TD_8_Q1_2,VAR3_TD_8_Q1_2,VAR4_TD_8_Q1_2,VAR1_TD_8_Q2_2,VAR2_TD_8_Q2_2,VAR3_TD_8_Q2_2,VAR4_TD_8_Q2_2,VAR1_TD_8_Q3_2,VAR2_TD_8_Q3_2,VAR3_TD_8_Q3_2,VAR4_TD_8_Q3_2,VAR1_TD_8_Q4_2,VAR2_TD_8_Q4_2,VAR3_TD_8_Q4_2,VAR4_TD_8_Q4_2,VAR1_TD_8_Q5_2,VAR2_TD_8_Q5_2,VAR3_TD_8_Q5_2,VAR4_TD_8_Q5_2,DER_CE_63_Q5,VAR5_TD_8_Q1_6,VAR5_TD_8_Q2_6,VAR5_TD_8_Q3_6,VAR5_TD_8_Q4_6,VAR5_TD_8_Q5_6,IS_WEEKEND,CONSECUTIVE_RUNNING,CONSECUTIVE_SLEEP,sitename,BCS_SCORE-bcs_recorded_date,BCS_SCORE-body_condition_score,BODY_WEIGHTS-weight_recorded_date,BODY_WEIGHTS-entered_weight_lb,DEMOGRAPHICS-gender,DEMOGRAPHICS-date_of_birth,DEMOGRAPHICS-randomization_date_time,DEMOGRAPHICS-enroll_dog,DEMOGRAPHICS-d0_expected_date,DEMOGRAPHICS-latest_d0_avail_date,DEMOGRAPHICS-day0_date,DEMOGRAPHICS-day0_age,OWNER_DAILY_DAIRY - total_amount_time_walked,MEDICATION - medication,BODY_WEIGHTS-DAY0_BODY_WEIGHT,BCS_SCORE-DAY0_body_condition_score,clinical_itt,clinical_pp,questionnaire_itt_extract,walking_900,running_900,active_900,walking_300,running_300,active_300,walking_60,running_60,active_60,longest_running_event,longest_walking_event,active_periods_count_rolling,most_common_hour_rolling,active_periods_count_fixed,most_common_hour_fixed,patient_id,dog_and_owner_name,study_food,weight,mixed_breed,intact,sex,date_of_birth,baseline_mean_soft_stiction,treatment_mean_soft_stiction,IS_QUALIFIED_NEW,Qualifying_Data_Day_NEW,NORMALIZED_QUALIFYING_STUDY_DAY_NEW,wearables_itt,wearables_pp,wearables_itt_extract,wearables_pp_extract,itt_failure_reason,pp_failure_reason
4,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,14-09-2019,-26,-18.0,26.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,1.0,YES,NaN,2877.0,22.0,6.0,122.5,6-406,406.0,130.772727,96.848400,76.25,209.00,152.373445,213.00,2.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,9.25,6.506407,6.50,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.000000,0.0,9.75,1.000000,1.00,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.000000,0.0,5.50,1.527525,1.50,0.0,18709.0,15.0,52.0,778.0,52-3510,3510.0,1247.266667,1172.669754,1029.0,18.75,4.320494,4.0,0.0,14.0,8.0,1.0,1.5,01-Apr,4.0,1.750000,1.035098,1.00,179.5,143.156092,161.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0-0,0.0,0.000000,0.00000,0.0,3.00,0.707107,0.50,94.0,0.0,10642.0,327.0,1.0,8.0,1-656,656.0,32.544343,70.789264,24.0,209.00,152.373445,213.00,13.0,15.0,12.0,1.0,1.0,01-Feb,2.0,1.250,0.452267,0.25,9.25,6.506407,6.50,3.0,25.0,12.0,1.0,1.0,01-Jun,6.0,2.083333,1.831955,1.5,9.75,1.000000,1.00,1.0,8.0,7.0,1.0,1.0,01-Feb,2.0,1.142857,0.377964,0.0,5.50,1.527525,1.50,1.0,8586.0,19.0,2.0,168.0,2-1835,1835.0,451.894737,575.011970,638.0,18.75,4.320494,4.0,1.0,2193.0,235.0,1.0,5.0,1-130,130.0,9.331915,12.725254,13.00,179.5,143.156092,161.0,8.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,4.0,1.0,3.0,01-Jun,6.0,4.666667,2.886751,2.5,3.00,0.707107,0.50,94.0,1.0,13656.0,340.0,1.0,16.0,1-596,596.0,40.164706,67.222011,31.25,209.00,152.373445,213.00,12.0,166.0,19.0,1.0,2.0,1-121,121.0,8.736842,27.292331,2.5,9.25,6.506407,6.50,1.0,38.0,14.0,1.0,1.0,01-Oct,10.0,2.714286,3.099096,1.75,9.75,1.000000,1.00,1.0,9.0,9.0,1.0,1.0,01-Jan,1.0,1.0,0.0,0.0,5.50,1.527525,1.50,9.0,5287.0,17.0,20.0,178.0,20-1108,1108.0,311.000000,331.799827,370.0,18.75,4.320494,4.0,1.0,2359.0,343.0,1.0,4.0,1-133,133.0,6.877551,10.740814,6.0,179.5,143.156092,161.0,8.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,85.0,5.0,1.0,33.5,Jan-44,44.0,39.166667,26.078411,20.0,3.00,0.707107,0.50,94.0,0.0,10075.0,149.0,1.0,23.0,1-520,520.0,67.617450,96.819671,90.0,209.00,152.373445,213.00,7.0,18.0,6.0,1.0,2.0,01-Jul,7.0,3.000000,2.449490,3.00,9.25,6.506407,6.50,0.0,38.0,13.0,1.0,2.0,01-Jul,7.0,2.923077,1.846688,2.0,9.75,1.000000,1.00,1.0,7.0,6.0,1.0,1.0,01-Feb,2.0,1.166667,0.408248,0.0,5.50,1.527525,1.50,1.0,10599.0,25.0,30.0,292.0,30-1708,1708.0,423.960000,454.251168,437.00,18.75,4.320494,4.0,2.0,860.0,132.0,1.0,4.0,Jan-56,56.0,6.515152,7.985182,7.0,179.5,143.156092,161.0,4.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,3.00,0.707107,0.50,94.0,3.0,37250,836,1,14.0,1-656,656,44.557416,78.365612,33.25,209.00,152.373445,213.00,32.0,199,37,1,1.0,1-121,121,5.378378,19.644552,1.0,9.25,6.506407,6.50,1.0,101,39,1,1.0,01-Oct,10,2.589744,2.336416,2.50,9.75,1.000000,1.00,2.0,24,22,1,1.0,01-Feb,2,1.090909,0.294245,0.0,5.50,1.527525,1.50,22.0,43181,75,2,360.0,Feb-10,3510,575.746667,741.450333,720.00,18.75,4.320494,4.0,3.0,5426,718,1,4.0,1-133,133,7.557103,11.016607,8.0,179.5,143.156092,161.0,20.0,0,0,0,0.0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98,12,1,22.0,Jan-44,44,25.777778,26.735035,21.0,3.00,0.707107,0.50,94.0,1.0,False,False,True,False,False,True,False,True,False,True,False,False,False,False,True,False,False,True,True,False,False,False,True,False,21600,21469,21515,21597,86181,14.0,2088.0,97.0,170.0,73.0,6.0,346.0,6430.0,9945.0,6800.0,770.0,23996.0,NaN,NaN,0.54,0.76,20.0,15.0,4.0,20.0,2.0,0.0,NaN,1.00,0.06,0.43,0.0,0.0,0.0,0.13,0.87,0.0,0.0,0.0,19:41.3,NaN,NaN,NaN,NaN,0.0,0.0,121.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,121.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,1,0,0,Quakertown,NaN,NaN,NaN,NaN,Neutered Male,03-07-2014,NaN,Yes,10-10-2019,07-11-2019,10-10-2019,5.0,NaN,NaN,NaN,NaN,True,True,True,1,0,1,0,0,0,4,0,4,0 days 00:00:11,0 days 00:02:13,2.0,9.0,0.0,NaN,EPRO-QT-02,Bandit Hocking,Peach,62.8,True,False,Male,03-07-2014 00:00,0.0,0.0,YES,1.0,-17.0,True,True,True,True,NaN,NaN
5,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,15-09-2019,-25,-17.0,27.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,2.0,YES,NaN,2371.0,25.0,1.0,104.0,1-279,279.0,94.840000,85.411592,124.00,175.00,116.008620,103.50,1.0,2.0,2.0,1.0,1.0,01-Jan,1.0,1.0,0.0,0.0,10.25,8.958236,5.25,2.0,7.0,2.0,3.0,3.5,03-Apr,4.0,3.5,0.707107,0.5,8.00,4.546061,3.50,2.0,3.0,2.0,1.0,1.5,01-Feb,2.0,1.5,0.707107,0.5,3.50,3.696846,2.00,0.0,19149.0,14.0,382.0,1076.5,382-3704,3704.0,1367.785714,970.481338,1354.5,16.25,2.449490,3.5,1.0,63.0,12.0,1.0,3.0,Jan-19,19.0,5.250000,6.136700,4.75,168.5,121.519546,102.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,4.0,1.0,2.0,01-Feb,2.0,2.333333,0.57735,0.5,3.50,1.534777,1.75,98.0,2.0,14523.0,304.0,1.0,18.0,1-460,460.0,47.773026,73.197669,38.5,175.00,116.008620,103.50,15.0,69.0,23.0,1.0,2.0,Jan-16,16.0,3.000,3.592922,2.50,10.25,8.958236,5.25,2.0,29.0,13.0,1.0,2.0,01-Jul,7.0,2.230769,1.739437,2.0,8.00,4.546061,3.50,1.0,10.0,9.0,1.0,1.0,01-Feb,2.0,1.111111,0.333333,0.0,3.50,3.696846,2.00,9.0,4921.0,19.0,2.0,105.0,2-1011,1011.0,259.000000,308.207362,381.5,16.25,2.449490,3.5,2.0,2045.0,306.0,1.0,4.0,Jan-42,42.0,6.683007,7.735431,8.00,168.5,121.519546,102.0,16.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.0,2.0,01-Jan,1.0,2.000000,0.000000,0.0,3.50,1.534777,1.75,98.0,3.0,12753.0,208.0,1.0,24.0,1-708,708.0,61.312500,95.300458,50.50,175.00,116.008620,103.50,7.0,8.0,8.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,10.25,8.958236,5.25,8.0,8.0,8.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.00,8.00,4.546061,3.50,8.0,1.0,1.0,1.0,1.0,01-Jan,1.0,1.0,0.0,0.0,3.50,3.696846,2.00,1.0,6475.0,19.0,3.0,192.0,Mar-68,2168.0,340.789474,511.630463,275.5,16.25,2.449490,3.5,1.0,2353.0,197.0,1.0,3.0,1-284,284.0,11.944162,33.209169,7.0,168.5,121.519546,102.0,7.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,3.50,1.534777,1.75,98.0,2.0,10516.0,163.0,2.0,24.0,2-615,615.0,64.515337,99.506769,57.0,175.00,116.008620,103.50,7.0,9.0,8.0,1.0,1.0,01-Feb,2.0,1.125000,0.353553,0.00,10.25,8.958236,5.25,1.0,23.0,9.0,1.0,2.0,01-May,5.0,2.555556,1.333333,1.0,8.00,4.546061,3.50,2.0,2.0,2.0,1.0,1.0,01-Jan,1.0,1.000000,0.000000,0.0,3.50,3.696846,2.00,2.0,10173.0,16.0,6.0,126.0,Jun-70,3370.0,635.812500,1058.471238,638.25,16.25,2.449490,3.5,1.0,872.0,159.0,1.0,4.0,Jan-32,32.0,5.484277,5.410790,6.5,168.5,121.519546,102.0,7.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,1.0,2.0,01-Jan,1.0,2.000000,0.000000,0.0,3.50,1.534777,1.75,98.0,5.0,40163,700,1,22.0,1-708,708,57.375714,87.545208,50.00,175.00,116.008620,103.50,27.0,88,41,1,1.0,Jan-16,16,2.146341,2.842191,1.0,10.25,8.958236,5.25,2.0,67,32,1,1.5,01-Jul,7,2.093750,1.467044,2.00,8.00,4.546061,3.50,2.0,16,14,1,1.0,01-Feb,2,1.142857,0.363137,0.0,3.50,3.696846,2.00,2.0,40718,65,2,194.0,Feb-04,3704,626.430769,866.813795,756.00,16.25,2.449490,3.5,3.0,5333,674,1,3.5,1-284,284,7.912463,19.046195,7.0,168.5,121.519546,102.0,8.0,0,0,0,0.0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15,14,1,2.0,01-Feb,2,2.142857,0.377964,0.0,3.50,1.534777,1.75,98.0,8.0,False,False,True,False,True,False,False,True,False,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,21595,21597,21598,21595,86385,11.0,1778.0,157.0,117.0,95.0,4.0,373.0,11314.0,9286.0,7860.0,334.0,28794.0,4.0,48.0,0.51,0.89,16.0,15.0,1.0,12.0,2.0,0.0,1.0,0.89,0.06,0.46,0.0,0.0,0.0,0.12,0.88,0.0,0.0,0.0,19:41.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,1,0,0,Quakertown,NaN,NaN,NaN,NaN,Neutered Male,03-07-2014,NaN,Yes,10-10-2019,07-11-2019,10-10-2019,5.0,NaN,NaN,NaN,NaN,True,True,True,0,0,0,0,0,0,8,0,8,0 days 00:00:16,0 days 00:04:44,5.0,15.0,2.0,15.0,EPRO-QT-02,Bandit Hocking,Peach,62.8,True,False,Male,03-07-2014 00:00,0.0,0.0,YES,2.0,-16.0,True,True,True,True,NaN,NaN

In [11]:
subgroup_and_activity = {
    
    "DEMOGRAPHICS-gender": 'Gender',
    "DEMOGRAPHICS-day0_age":'Day 0 age',
    "weight": 'Day 0 body weight',
    "sitename": 'Site',
    "MEDICATION - medication": 'Baseline period pain medications',
    "OWNER_DAILY_DAIRY - total_amount_time_walked": 'Owner Daily Diary',
    'IS_WEEKEND': 'weekend vs. weekday',
    'VAR_TD_1_Q5_2': 'Resting (All Day)',
    'VAR_TD_3_Q5_2': 'Running (All Day)',
    'VAR_TD_5_Q5_2': 'Scratching (All Day)',
    'VAR_TD_4_Q5_2': 'Shaking (All Day)',
    'VAR_TD_12_Q5_2': 'Sleeping (All Day)',
    'VAR_TD_2_Q5_2': 'Walking (All Day)',
    'VAR_IDX_11_Q5_2': 'Sleep Quality'
    
}

subgroups = {
    
    "DEMOGRAPHICS-gender": 'Gender',
    "DEMOGRAPHICS-day0_age":'Day 0 age',
    "weight": 'Day 0 body weight',
    "sitename": 'Site',
    "MEDICATION - medication": 'Baseline period pain medications',
    "OWNER_DAILY_DAIRY - total_amount_time_walked": 'Owner Daily Diary',
    'IS_WEEKEND': 'weekend vs. weekday'
}

In [12]:
def age_category_converter(age):
    if (age < 7):
        return "Adult"
    elif (age>=7 and age < 11):
        return "Senior younger than 11"
    elif (age>= 11):
        return "Senior older than 11"
    else:
        return np.nan

def body_weight_category(x):
    if x is np.nan:
        return np.nan
    elif x>0 and x<=20:
        return 'up to 20 lbs'
    elif x>20 and x<=50:
        return '>20 lbs & <=50 lbs'
    elif x>50:
        return '>50 lbs'
    
def diary_category_converter(df):
    # Calculate the mean and median of 'Owner Daily Diary'
    mean_diary = df['Owner Daily Diary'].mean()
    median_diary = df['Owner Daily Diary'].median()

    # Create a new column 'Owner Daily Diary,mean.categorical'
    df['Owner Daily Diary.mean.categorical'] = df['Owner Daily Diary'].apply(
        lambda x: 'Above Mean' if x > mean_diary else 'Below Mean'
    )

    df['Owner Daily Diary.median.categorical'] = df['Owner Daily Diary'].apply(
        lambda x: 'Above Median' if x > median_diary else 'Below Median'
    )

def map_weekend_weekday(value):
    if value == 0:
        return 'Weekday'
    elif value == 1:
        return 'Weekend'

In [13]:
subgroup_study_cols = list(data.columns[:20]) + list(subgroup_and_activity.keys())
subgroup_df = data[subgroup_study_cols]
subgroup_df.rename(columns=subgroup_and_activity, inplace=True)

/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/pandas/core/frame.py:4304: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [14]:
subgroup_df['Gender'].unique()

array(['Neutered Male', 'Spayed Female', 'Intact Male', nan], dtype=object)

In [15]:
# Convert to categorical subgroups
subgroup_df['Age.category'] = subgroup_df['Day 0 age'].apply(age_category_converter)
subgroup_df['Day 0 body weight'] = subgroup_df['Day 0 body weight'].apply(lambda x: float(x) if pd.notna(x) else np.nan)
subgroup_df['Day 0 body weight (category)'] = subgroup_df['Day 0 body weight'].apply(body_weight_category)
subgroup_df['ISweekend.categorical'] = subgroup_df['weekend vs. weekday'].apply(lambda x: map_weekend_weekday(x))
diary_category_converter(subgroup_df)

/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/conda/envs/hillsadvancedml_envi/lib/python3.7/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
subgroup_df.head()

,PET_ID,EXTERNAL_ID,DEVICE_ID,STUDY_ID,STUDY_NAME,PET_NAME,DATE,NORMALIZED_STUDY_DAY,NORMALIZED_QUALIFYING_STUDY_DAY,STUDY_DAY_COUNTER,STUDY_GROUP,BASELINE_START,START_DATE,ENROLLMENT_DATE,COMPLETION_DATE,END_DATE,EXCESSIVE_RUNNING,TIMEZONE,QUALIFYING_DATA_DAY,IS_QUALIFIED,Gender,Day 0 age,Day 0 body weight,Site,Baseline period pain medications,Owner Daily Diary,weekend vs. weekday,Resting (All Day),Running (All Day),Scratching (All Day),Shaking (All Day),Sleeping (All Day),Walking (All Day),Sleep Quality,Age.category,Day 0 body weight (category),ISweekend.categorical,Owner Daily Diary.mean.categorical,Owner Daily Diary.median.categorical
4,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,14-09-2019,-26,-18.0,26.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,1.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,1,37250,199,101,24,43181,5426,94.0,Adult,>50 lbs,Weekend,Below Mean,Below Median
5,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,15-09-2019,-25,-17.0,27.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,2.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,1,40163,88,67,16,40718,5333,98.0,Adult,>50 lbs,Weekend,Below Mean,Below Median
10,3347,EPRO-QT-02,13145,1894,Aging Study,Bandit,25-09-2019,-15,-15.0,37.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,4.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,0,36173,43,101,11,46327,3702,94.0,Adult,>50 lbs,Weekday,Below Mean,Below Median
11,3347,EPRO-QT-02,13145,1894,Aging Study,Bandit,26-09-2019,-14,-14.0,38.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,5.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,0,28838,30,91,9,54675,2723,96.0,Adult,>50 lbs,Weekday,Below Mean,Below Median
12,3347,EPRO-QT-02,13145,1894,Aging Study,Bandit,27-09-2019,-13,-13.0,39.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,6.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,0,36816,96,52,15,42264,7044,94.0,Adult,>50 lbs,Weekday,Below Mean,Below Median

In [17]:
activities = ['Resting (All Day)', 'Running (All Day)', 'Scratching (All Day)', 'Shaking (All Day)', 'Sleeping (All Day)', 'Walking (All Day)']

In [18]:
def calculate_statistics(df, column_name, subgroup_column):
    grouped = df.groupby(subgroup_column)
    statistics = grouped[column_name].agg(['mean', 'std', 'median', lambda x: x.quantile(0.75) - x.quantile(0.25)])
    
    statistics.columns = ['Mean', 'SD', 'Median', 'IQR']

    # Round the statistics to 2 decimal places
    statistics_rounded = statistics.round(2)

    return statistics_rounded

In [19]:
def statistical_tests(df, column_name, subgroup_column):

    grouped_data = df.groupby(subgroup_column)[column_name]
    
    # Kruskal-Wallis test for multiple subgroups
    kruskal_stat, p_value_kruskal = stats.kruskal(*[grouped_data.get_group(group) for group in df[subgroup_column].unique()])
    
    # Pairwise Mann-Whitney U test for two subgroups
    subgroup_list = df[subgroup_column].unique()
    pairwise_tests = []
    for i in range(len(subgroup_list)):
        for j in range(i+1, len(subgroup_list)):
            group1_data = grouped_data.get_group(subgroup_list[i])
            group2_data = grouped_data.get_group(subgroup_list[j])
            u_stat, p_value_mannwhitney = stats.mannwhitneyu(group1_data, group2_data, alternative='two-sided')
            pairwise_tests.append((subgroup_list[i], subgroup_list[j], u_stat, p_value_mannwhitney))
    
    print(f"Kruskal-Wallis Test Results for '{column_name}' across '{subgroup_column}':")
    print(f"Kruskal-Wallis Statistic: {kruskal_stat:.4f}")
    print(f"P-Value: {p_value_kruskal:.4f}\n")

    #print("Pairwise Mann-Whitney U Test Results:")
    #for group1, group2, u_stat, p_value in pairwise_tests:
       # print(f"{group1} vs. {group2}:")
       # print(f"Mann-Whitney U Statistic: {u_stat:.4f}")
       # print(f"P-Value: {p_value:.4f}")
       # print()

In [20]:
def statistical_tests(df, column_name, subgroup_column):
    grouped_data = df.groupby(subgroup_column)[column_name]
    
    # Kruskal-Wallis test for multiple subgroups
    kruskal_stat, p_value_kruskal = stats.kruskal(*[grouped_data.get_group(group) for group in df[subgroup_column].unique()])

    # Formatting Kruskal-Wallis test results
    kruskal_data = [[kruskal_stat, p_value_kruskal]]
    kruskal_headers = ["Statistic", 'P-value']
    kruskal_stubs = ["Kruskal-Wallis Test"]
    tbl_kruskal = SimpleTable(kruskal_data, kruskal_headers, kruskal_stubs,
                              title=f"Kruskal-Wallis Test Results for '{column_name}' across '{subgroup_column}'")
    print(tbl_kruskal)
    
    # Conclusion based on p-value
    if p_value_kruskal < 0.05:
        conclusion = 'We reject the null hypothesis. At least one group median is different from others.'
    else:
        conclusion = 'We could not reject the null hypothesis. The medians of all groups are equal.'

    print(conclusion)

## Age Subgroup

In [21]:
for activity in activities:
    print(f"{activity} Statistics for Age")
    stats_df = calculate_statistics(subgroup_df, activity, 'Age.category')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Age

                            Mean       SD   Median      IQR
Age.category
Adult                   32258.15  6103.12  32254.5  7948.75
Senior older than 11    33370.05  5402.90  33130.0  7058.50
Senior younger than 11  31134.05  6109.67  31264.5  7849.00

Running (All Day) Statistics for Age

                          Mean      SD  Median     IQR
Age.category
Adult                   189.24  219.91     127  152.25
Senior older than 11    147.50  223.76      80  118.00
Senior younger than 11  192.12  238.12     118  188.50

Scratching (All Day) Statistics for Age

                         Mean     SD  Median    IQR
Age.category
Adult                   62.01  47.27      47  45.75
Senior older than 11    56.84  85.75      24  35.00
Senior younger than 11  62.37  70.30      42  53.00

Shaking (All Day) Statistics for Age

                         Mean     SD  Median    IQR
Age.category
Adult                   30.50  15.90      27  19.75
Senior older than 11    27.14  18.64      22  24.00
Senior younger than 11  31.57  17.84      28  21.00

Sleeping (All Day) Statistics for Age

                            Mean       SD  Median      IQR
Age.category
Adult                   48131.40  7271.80   47634  9099.00
Senior older than 11    46445.17  6252.87   46852  8568.00
Senior younger than 11  49101.35  7507.12   48742  9090.25

Walking (All Day) Statistics for Age

                           Mean       SD  Median      IQR
Age.category
Adult                   4609.15  1869.34    4411  2468.25
Senior older than 11    5271.39  2321.06    4736  2901.00
Senior younger than 11  4631.16  2196.22    4239  2628.25

In [22]:
subgroup_age = subgroup_df.dropna(subset=['Age.category']).copy()

In [23]:
subgroup_age.head()

,PET_ID,EXTERNAL_ID,DEVICE_ID,STUDY_ID,STUDY_NAME,PET_NAME,DATE,NORMALIZED_STUDY_DAY,NORMALIZED_QUALIFYING_STUDY_DAY,STUDY_DAY_COUNTER,STUDY_GROUP,BASELINE_START,START_DATE,ENROLLMENT_DATE,COMPLETION_DATE,END_DATE,EXCESSIVE_RUNNING,TIMEZONE,QUALIFYING_DATA_DAY,IS_QUALIFIED,Gender,Day 0 age,Day 0 body weight,Site,Baseline period pain medications,Owner Daily Diary,weekend vs. weekday,Resting (All Day),Running (All Day),Scratching (All Day),Shaking (All Day),Sleeping (All Day),Walking (All Day),Sleep Quality,Age.category,Day 0 body weight (category),ISweekend.categorical,Owner Daily Diary.mean.categorical,Owner Daily Diary.median.categorical
4,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,14-09-2019,-26,-18.0,26.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,1.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,1,37250,199,101,24,43181,5426,94.0,Adult,>50 lbs,Weekend,Below Mean,Below Median
5,3347,EPRO-QT-02,13034,1894,Aging Study,Bandit,15-09-2019,-25,-17.0,27.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,2.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,1,40163,88,67,16,40718,5333,98.0,Adult,>50 lbs,Weekend,Below Mean,Below Median
10,3347,EPRO-QT-02,13145,1894,Aging Study,Bandit,25-09-2019,-15,-15.0,37.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,4.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,0,36173,43,101,11,46327,3702,94.0,Adult,>50 lbs,Weekday,Below Mean,Below Median
11,3347,EPRO-QT-02,13145,1894,Aging Study,Bandit,26-09-2019,-14,-14.0,38.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,5.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,0,28838,30,91,9,54675,2723,96.0,Adult,>50 lbs,Weekday,Below Mean,Below Median
12,3347,EPRO-QT-02,13145,1894,Aging Study,Bandit,27-09-2019,-13,-13.0,39.0,Unassigned,10-10-2019,10-09-2019,10-10-2019,02-01-2020,05-02-2020,0,Central Standard Time,6.0,YES,Neutered Male,5.0,62.8,Quakertown,NaN,NaN,0,36816,96,52,15,42264,7044,94.0,Adult,>50 lbs,Weekday,Below Mean,Below Median

In [24]:
for activity in activities:
    print(f"{activity} Statistical Tests for Age")
    statistical_tests(subgroup_age, activity, 'Age.category')
    print("\n")

Resting (All Day) Statistical Tests for Age
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'Age.category'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 62.45477374226148 2.742320420448863e-14
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Running (All Day) Statistical Tests for Age
Kruskal-Wallis Test Results for 'Running (All Day)' across 'Age.category'
============================================================
                        Statistic            P-value
------------------------------------------------------------
Kruskal-Wallis Test 71.43092245761687 3.0829910907356837e-16
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Age
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'Age.category'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 120.54128510440064 6.68024697144896e-27
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Shaking (All Day) Statistical Tests for Age
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'Age.category'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 57.92628424829446 2.639168973333166e-13
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Sleeping (All Day) Statistical Tests for Age
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'Age.category'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 67.61212308278203 2.080721801608232e-15
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Walking (All Day) Statistical Tests for Age
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'Age.category'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 43.94920112340073 2.861226469049303e-10
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.

## Gender Subgroup

In [25]:
for activity in activities:
    print(f"{activity} Statistics for Gender")
    stats_df = calculate_statistics(subgroup_df, activity, 'Gender')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Gender

                   Mean       SD  Median      IQR
Gender
Intact Male    36115.16  6118.13   35127  8601.00
Neutered Male  32354.82  5771.00   32196  7507.75
Spayed Female  31736.84  5937.21   31984  7723.00

Running (All Day) Statistics for Gender

                 Mean      SD  Median    IQR
Gender
Intact Male    180.07  110.56     147  140.0
Neutered Male  179.07  229.50     107  149.0
Spayed Female  167.60  222.47      94  161.5

Scratching (All Day) Statistics for Gender

                Mean     SD  Median    IQR
Gender
Intact Male    29.93  18.65      27  14.00
Neutered Male  70.83  83.42      41  60.75
Spayed Female  51.62  57.34      34  50.00

Shaking (All Day) Statistics for Gender

                Mean     SD  Median  IQR
Gender
Intact Male    18.60  11.91      18   20
Neutered Male  29.44  15.61      26   21
Spayed Female  29.69  18.82      25   22

Sleeping (All Day) Statistics for Gender

                   Mean       SD   Median      IQR
Gender
Intact Male    41597.23  5298.61  42084.0  7685.00
Neutered Male  47776.81  6887.62  47770.5  9366.25
Spayed Female  48613.23  7239.10  48257.0  9037.00

Walking (All Day) Statistics for Gender

                  Mean       SD  Median     IQR
Gender
Intact Male    7545.02  2187.65  6843.0  2649.0
Neutered Male  4792.52  2130.51  4381.5  2581.0
Spayed Female  4672.29  2114.90  4357.0  2632.5

In [26]:
for activity in activities:
    print(f"{activity} Statistical Tests for Gender")
    statistical_tests(subgroup_age, activity, 'Gender')
    print("\n")

Resting (All Day) Statistical Tests for Gender
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'Gender'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 28.05580670548425 8.086470028563254e-07
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Running (All Day) Statistical Tests for Gender
Kruskal-Wallis Test Results for 'Running (All Day)' across 'Gender'
============================================================
                        Statistic            P-value
------------------------------------------------------------
Kruskal-Wallis Test 36.48150259617547 1.1971328974656438e-08
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Gender
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'Gender'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 75.44068216030078 4.152063753971147e-17
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Shaking (All Day) Statistical Tests for Gender
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'Gender'
============================================================
                        Statistic             P-value
------------------------------------------------------------
Kruskal-Wallis Test 27.741979850632116 9.460315426050912e-07
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Sleeping (All Day) Statistical Tests for Gender
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'Gender'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 65.05294158124366 7.480544655851047e-15
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Walking (All Day) Statistical Tests for Gender
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'Gender'
============================================================
                        Statistic            P-value
------------------------------------------------------------
Kruskal-Wallis Test 80.91325503686504 2.6909765445807165e-18
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.

## Body Weight Subgroup

In [27]:
for activity in activities:
    print(f"{activity} Statistics for Day 0 Body Weight")
    stats_df = calculate_statistics(subgroup_df, activity, 'Day 0 body weight (category)')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Day 0 Body Weight

                                  Mean       SD   Median      IQR
Day 0 body weight (category)
>20 lbs & <=50 lbs            33819.16  5544.87  33995.0  7048.75
>50 lbs                       31077.04  5941.62  31180.5  7764.25
up to 20 lbs                  33550.68  4831.65  33277.5  5887.75

Running (All Day) Statistics for Day 0 Body Weight

                                Mean      SD  Median     IQR
Day 0 body weight (category)
>20 lbs & <=50 lbs            248.39  293.83   151.0  222.75
>50 lbs                       118.44  159.09    72.5   92.00
up to 20 lbs                  229.36  202.86   180.0  167.25

Scratching (All Day) Statistics for Day 0 Body Weight

                                Mean      SD  Median  IQR
Day 0 body weight (category)
>20 lbs & <=50 lbs             49.30   55.31      32   45
>50 lbs                        48.17   47.55      33   44
up to 20 lbs                  171.08  139.72     132  199

Shaking (All Day) Statistics for Day 0 Body Weight

                               Mean     SD  Median  IQR
Day 0 body weight (category)
>20 lbs & <=50 lbs            31.01  19.11      27   24
>50 lbs                       26.67  14.90      24   18
up to 20 lbs                  39.75  14.94      40   20

Sleeping (All Day) Statistics for Day 0 Body Weight

                                  Mean       SD   Median      IQR
Day 0 body weight (category)
>20 lbs & <=50 lbs            45881.46  6496.24  45926.5  8596.50
>50 lbs                       49572.92  7075.04  49403.5  8947.75
up to 20 lbs                  46100.93  6136.56  46877.0  7971.25

Walking (All Day) Statistics for Day 0 Body Weight

                                 Mean       SD  Median      IQR
Day 0 body weight (category)
>20 lbs & <=50 lbs            5375.83  2412.78    4826  2933.75
>50 lbs                       4419.20  1947.71    4137  2529.75
up to 20 lbs                  4979.10  2129.19    4531  2432.00

In [28]:
subgroup_body_weight = subgroup_df.dropna(subset=['Day 0 body weight (category)']).copy()

In [29]:
for activity in activities:
    print(f"{activity} Statistical Tests for Body Weight")
    statistical_tests(subgroup_body_weight, activity, 'Day 0 body weight (category)')
    print("\n")

Resting (All Day) Statistical Tests for Body Weight
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'Day 0 body weight (category)'
=============================================================
                        Statistic             P-value
-------------------------------------------------------------
Kruskal-Wallis Test 137.95054413946053 1.1076943801540841e-30
-------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Running (All Day) Statistical Tests for Body Weight
Kruskal-Wallis Test Results for 'Running (All Day)' across 'Day 0 body weight (category)'
============================================================
                        Statistic             P-value
------------------------------------------------------------
Kruskal-Wallis Test 318.58106316635656 6.622182023268896e-70
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Body Weight
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'Day 0 body weight (category)'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 273.3300681740373 4.437412749945401e-60
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Shaking (All Day) Statistical Tests for Body Weight
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'Day 0 body weight (category)'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 152.88124420522124 6.34248761117913e-34
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Sleeping (All Day) Statistical Tests for Body Weight
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'Day 0 body weight (category)'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 182.6414874487884 2.187282696052206e-40
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Walking (All Day) Statistical Tests for Body Weight
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'Day 0 body weight (category)'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 94.29427268539239 3.343942868101951e-21
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.

## Site Subgropup

In [30]:
subgroup_site_greater_than_1 = subgroup_df[subgroup_df['Site']\
                                                     .isin(subgroup_df['Site'].value_counts()\
                                                           [subgroup_df['Site'].value_counts()>1].index)]

In [31]:
for activity in activities:
    print(f"{activity} Statistics for Site")
    stats_df = calculate_statistics(subgroup_site_greater_than_1, activity, 'Site')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Site

                                       Mean       SD   Median       IQR
Site
Animal Doctor                      31480.18  4069.67  31176.5   3699.75
Blue Hills                         30527.43  5183.01  29934.5   6281.25
Braden River                       28639.31  5831.64  29515.0   7705.50
Chippens Hill Phase 2              31912.57  7024.84  33305.0   6309.00
Chippens Hill Veterinary Hospital  30695.68  5135.88  30927.5   6956.75
Eastside Animal Hospital           29221.02  5415.63  28304.0   7330.50
Family                             34895.36  6293.36  35844.5   8036.75
Greece                             37391.86  5713.79  36961.0  10473.25
Northgate                          34285.47  4159.45  34649.0   5821.25
Northwest Freeway Animal Hospital  33393.95  3031.15  33441.5   5354.00
Quakertown                         31604.43  6357.29  31677.0   8344.75
Quakertown Phase 2                 32976.95  5919.78  32549.0   7362.00
Raintree                           31752.26  5366.79  31791.0   7051.00
Stanley Vet Clnic                  33333.30  6676.03  32571.0   7831.25
Trusty Vet                         26759.20  3033.10  26235.0   4302.75
Wakarusa Veterinary Hospital       32421.54  5471.85  32089.5   9492.25
Wamego                             37409.24  3901.55  37105.5   5338.75

Running (All Day) Statistics for Site

                                     Mean      SD  Median     IQR
Site
Animal Doctor                      277.64  322.38   183.0  141.00
Blue Hills                          61.64  140.44    31.0   30.25
Braden River                        61.72   50.48    53.0   43.00
Chippens Hill Phase 2               85.26  105.76    64.0   88.00
Chippens Hill Veterinary Hospital  118.89   94.24    88.5   79.75
Eastside Animal Hospital            75.11   96.90    58.0   48.25
Family                             193.64  204.32   163.5  184.25
Greece                             185.93  118.09   149.5  148.75
Northgate                          100.73   87.33    69.0   94.75
Northwest Freeway Animal Hospital  263.10  135.07   246.5  152.75
Quakertown                         204.32  225.35   108.5  232.00
Quakertown Phase 2                 247.45  312.35   127.0  227.00
Raintree                           196.44  222.25   126.0  184.00
Stanley Vet Clnic                  260.46  177.86   205.0  145.00
Trusty Vet                         663.20  343.48   553.5  322.75
Wakarusa Veterinary Hospital       146.00  106.16   121.5   93.25
Wamego                             107.63  104.38    69.5   68.50

Scratching (All Day) Statistics for Site

                                     Mean      SD  Median     IQR
Site
Animal Doctor                       75.32   80.88    26.0  125.75
Blue Hills                          31.73   23.90    24.5   28.25
Braden River                        80.24   97.63    50.0   52.50
Chippens Hill Phase 2               50.50   84.34    24.0   28.00
Chippens Hill Veterinary Hospital   52.05   52.06    31.5   30.75
Eastside Animal Hospital            51.74   73.39    31.0   39.75
Family                             151.17  149.10    85.5  172.50
Greece                              24.89   14.64    24.0   15.00
Northgate                           67.40   79.15    37.0   77.00
Northwest Freeway Animal Hospital   38.15   17.46    38.0   23.75
Quakertown                          72.86   63.50    49.0   57.25
Quakertown Phase 2                  53.43   51.22    39.0   50.00
Raintree                            58.19   58.42    41.0   49.50
Stanley Vet Clnic                  109.11   67.94    98.0  105.25
Trusty Vet                          25.65   23.90    18.5   11.25
Wakarusa Veterinary Hospital        38.97   24.90    29.5   31.75
Wamego                               8.39    4.10     8.0    4.75

Shaking (All Day) Statistics for Site

                                    Mean     SD  Median    IQR
Site
Animal Doctor                      17.20   7.34    17.0  10.25
Blue Hills                         18.46   8.70    18.5  13.00
Braden River                       23.49  11.39    21.0  12.00
Chippens Hill Phase 2              23.58  19.46    17.0  17.00
Chippens Hill Veterinary Hospital  19.61   8.06    18.0   9.00
Eastside Animal Hospital           19.43  10.69    17.0   8.00
Family                             33.21  18.72    28.0  34.00
Greece                             14.04   3.98    14.0   6.50
Northgate                          33.59  21.19    27.5  20.00
Northwest Freeway Animal Hospital  46.00  27.67    36.5  29.25
Quakertown                         25.01  14.52    21.0  13.00
Quakertown Phase 2                 33.21  17.12    32.0  20.00
Raintree                           33.67  14.98    31.0  19.00
Stanley Vet Clnic                  40.61  27.79    39.0  43.25
Trusty Vet                         23.15  13.83    19.5  11.50
Wakarusa Veterinary Hospital       30.93  14.11    29.5  19.25
Wamego                             20.03   8.19    19.0   8.75

Sleeping (All Day) Statistics for Site

                                       Mean       SD   Median       IQR
Site
Animal Doctor                      49472.57  5241.38  49938.5   4674.00
Blue Hills                         50971.93  5776.39  51424.0   8736.00
Braden River                       52709.97  7677.39  52689.0  10562.00
Chippens Hill Phase 2              48700.95  8527.60  47299.0   7220.00
Chippens Hill Veterinary Hospital  49925.99  6295.03  49189.5   8672.75
Eastside Animal Hospital           50191.23  6260.03  50584.0   8806.75
Family                             44834.81  7218.18  43734.5   8837.50
Greece                             41582.18  8445.62  42701.5  15734.50
Northgate                          46211.85  5464.86  45940.0   7548.50
Northwest Freeway Animal Hospital  47029.20  2799.22  47117.0   3031.25
Quakertown                         48756.36  7458.02  48208.5   9781.50
Quakertown Phase 2                 47074.01  7176.61  47139.0  10952.50
Raintree                           48141.56  6386.34  48004.0   8475.00
Stanley Vet Clnic                  45574.75  8540.71  46901.0  10977.50
Trusty Vet                         51865.50  4637.59  52858.5   6215.00
Wakarusa Veterinary Hospital       48243.96  5966.68  48634.5   9544.25
Wamego                             42390.42  5220.11  42629.0   6911.00

Walking (All Day) Statistics for Site

                                      Mean       SD  Median      IQR
Site
Animal Doctor                      3729.48  1064.99  3487.5  1144.50
Blue Hills                         3572.04  1213.48  3492.5  1498.25
Braden River                       3500.16  1531.35  3265.0  2036.50
Chippens Hill Phase 2              4524.30  2369.85  4291.0  3113.00
Chippens Hill Veterinary Hospital  4632.65  1851.51  4829.5  2876.00
Eastside Animal Hospital           5345.80  1745.38  4905.0  1753.00
Family                             5270.27  2458.59  5185.5  3741.00
Greece                             5468.61  2144.94  5413.5  3441.75
Northgate                          4799.50  1590.33  4780.0  2462.00
Northwest Freeway Animal Hospital  4629.60   969.76  4721.5  1219.75
Quakertown                         4997.27  1790.84  4810.0  2120.50
Quakertown Phase 2                 5067.43  2695.48  4220.0  3416.50
Raintree                           4878.03  1982.41  4492.0  2385.00
Stanley Vet Clnic                  5313.44  2577.75  4765.5  3624.75
Trusty Vet                         5787.80  1333.67  5797.0  1447.00
Wakarusa Veterinary Hospital       4397.49  1381.36  4459.5  1661.25
Wamego                             6156.32  1858.59  5920.0  2038.00

In [32]:
for activity in activities:
    print(f"{activity} Statistical Tests for Site")
    statistical_tests(subgroup_site_greater_than_1, activity, 'Site')
    print("\n")

Resting (All Day) Statistical Tests for Site
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'Site'
============================================================
                        Statistic             P-value
------------------------------------------------------------
Kruskal-Wallis Test 245.45334807568733 4.424941173319459e-43
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Running (All Day) Statistical Tests for Site
Kruskal-Wallis Test Results for 'Running (All Day)' across 'Site'
============================================================
                        Statistic            P-value
------------------------------------------------------------
Kruskal-Wallis Test 631.0932343764138 5.761964170018081e-124
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Site
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'Site'
============================================================
                        Statistic            P-value
------------------------------------------------------------
Kruskal-Wallis Test 402.3861322382883 1.1511227693669122e-75
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Shaking (All Day) Statistical Tests for Site
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'Site'
=============================================================
                        Statistic             P-value
-------------------------------------------------------------
Kruskal-Wallis Test 529.8404726162008 1.6503004003297532e-102
-------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Sleeping (All Day) Statistical Tests for Site
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'Site'
============================================================
                        Statistic             P-value
------------------------------------------------------------
Kruskal-Wallis Test 216.12855513520876 4.269904325539165e-37
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Walking (All Day) Statistical Tests for Site
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'Site'
============================================================
                        Statistic             P-value
------------------------------------------------------------
Kruskal-Wallis Test 201.74647746304467 3.517282108471948e-34
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.

## Owner Daily Diary time spent walking Subgroup

In [33]:
for activity in activities:
    print(f"{activity} Statistics for Owner Daily Diary")
    stats_df = calculate_statistics(subgroup_df, activity, 'Owner Daily Diary.mean.categorical')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Owner Daily Diary

                                        Mean       SD   Median   IQR
Owner Daily Diary.mean.categorical
Above Mean                          30610.88  2874.35  30643.5  2736
Below Mean                          32099.46  5884.50  32140.0  7568

Running (All Day) Statistics for Owner Daily Diary

                                      Mean      SD  Median     IQR
Owner Daily Diary.mean.categorical
Above Mean                          615.25  147.52   595.5  160.25
Below Mean                          170.39  222.19    99.0  153.00

Scratching (All Day) Statistics for Owner Daily Diary

                                      Mean     SD  Median    IQR
Owner Daily Diary.mean.categorical
Above Mean                          113.12  40.58   105.5  35.75
Below Mean                           59.13  70.35    36.0  52.00

Shaking (All Day) Statistics for Owner Daily Diary

                                     Mean     SD  Median   IQR
Owner Daily Diary.mean.categorical
Above Mean                          27.25   6.36      28  11.5
Below Mean                          29.25  17.37      26  21.0

Sleeping (All Day) Statistics for Owner Daily Diary

                                        Mean       SD   Median      IQR
Owner Daily Diary.mean.categorical
Above Mean                          43910.50  3730.82  44919.5  7128.75
Below Mean                          48157.37  7103.13  47983.0  9140.00

Walking (All Day) Statistics for Owner Daily Diary

                                        Mean       SD   Median   IQR
Owner Daily Diary.mean.categorical
Above Mean                          10950.00  1844.85  10674.5  2115
Below Mean                           4732.27  2143.66   4370.0  2666

In [34]:
for activity in activities:
    print(f"{activity} Statistics for Owner Daily Diary")
    stats_df = calculate_statistics(subgroup_df, activity, 'Owner Daily Diary.median.categorical')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Owner Daily Diary

                                         Mean       SD  Median     IQR
Owner Daily Diary.median.categorical
Above Median                          30483.4  2960.01   31467  1755.0
Below Median                          32098.2  5882.36   32138  7556.5

Running (All Day) Statistics for Owner Daily Diary

                                        Mean      SD  Median  IQR
Owner Daily Diary.median.categorical
Above Median                          613.00  136.41     598   97
Below Median                          170.83  222.59      99  154

Scratching (All Day) Statistics for Owner Daily Diary

                                       Mean     SD  Median  IQR
Owner Daily Diary.median.categorical
Above Median                          107.2  47.10     103   26
Below Median                           59.2  70.35      36   53

Shaking (All Day) Statistics for Owner Daily Diary

                                       Mean     SD  Median  IQR
Owner Daily Diary.median.categorical
Above Median                          30.40   5.59      32    4
Below Median                          29.25  17.36      26   21

Sleeping (All Day) Statistics for Owner Daily Diary

                                          Mean       SD   Median      IQR
Owner Daily Diary.median.categorical
Above Median                          43302.40  3719.67  43112.0  6681.00
Below Median                          48154.17  7101.21  47977.5  9141.25

Walking (All Day) Statistics for Owner Daily Diary

                                          Mean       SD   Median     IQR
Owner Daily Diary.median.categorical
Above Median                          11598.80  1873.27  11977.0  2283.0
Below Median                           4737.35  2149.01   4373.5  2673.5

In [35]:
for activity in activities:
    print(f"{activity} Statistical Tests for Owner Daily Diary")
    statistical_tests(subgroup_df, activity, 'Owner Daily Diary.mean.categorical')
    print("\n")

Resting (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'Owner Daily Diary.mean.categorical'
=========================================================
                        Statistic           P-value
---------------------------------------------------------
Kruskal-Wallis Test 0.906425562895824 0.34106460425646284
---------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Running (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Running (All Day)' across 'Owner Daily Diary.mean.categorical'
=============================================================
                        Statistic             P-value
-------------------------------------------------------------
Kruskal-Wallis Test 19.482541437143087 1.0152336852503346e-05
-------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'Owner Daily Diary.mean.categorical'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 11.59978211474195 0.0006595954664857534
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Shaking (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'Owner Daily Diary.mean.categorical'
==========================================================
                         Statistic           P-value
----------------------------------------------------------
Kruskal-Wallis Test 0.08689957680632518 0.7681563368645321
----------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Sleeping (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'Owner Daily Diary.mean.categorical'
==========================================================
                        Statistic            P-value
----------------------------------------------------------
Kruskal-Wallis Test 3.9932963608414846 0.04568161155506834
----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Walking (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'Owner Daily Diary.mean.categorical'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 21.78025787327926 3.057298844266496e-06
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.

In [36]:
for activity in activities:
    print(f"{activity} Statistical Tests for Owner Daily Diary")
    statistical_tests(subgroup_df, activity, 'Owner Daily Diary.median.categorical')
    print("\n")

Resting (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'Owner Daily Diary.median.categorical'
=========================================================
                        Statistic           P-value
---------------------------------------------------------
Kruskal-Wallis Test 0.626010655508816 0.42882241879564686
---------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Running (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Running (All Day)' across 'Owner Daily Diary.median.categorical'
=============================================================
                        Statistic             P-value
-------------------------------------------------------------
Kruskal-Wallis Test 12.204667644859107 0.00047670094111586643
-------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'Owner Daily Diary.median.categorical'
==========================================================
                        Statistic           P-value
----------------------------------------------------------
Kruskal-Wallis Test 6.492813546541846 0.010831142227340421
----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Shaking (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'Owner Daily Diary.median.categorical'
==========================================================
                        Statistic            P-value
----------------------------------------------------------
Kruskal-Wallis Test 0.6758093319823313 0.41103351151623924
----------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Sleeping (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'Owner Daily Diary.median.categorical'
=========================================================
                        Statistic           P-value
---------------------------------------------------------
Kruskal-Wallis Test 3.309922360428282 0.06886274544776115
---------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Walking (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'Owner Daily Diary.median.categorical'
=============================================================
                        Statistic             P-value
-------------------------------------------------------------
Kruskal-Wallis Test 14.051467501841815 0.00017787497738297857
-------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.

## Weekend vs. Weekday Subgroup

In [37]:
for activity in activities:
    print(f"{activity} Statistics for Day 0 Body Weight")
    stats_df = calculate_statistics(subgroup_df, activity, 'ISweekend.categorical')
    display(stats_df)
    print("\n")

Resting (All Day) Statistics for Day 0 Body Weight

                           Mean       SD  Median      IQR
ISweekend.categorical
Weekday                31671.99  5822.26   31707  7511.75
Weekend                33150.26  5889.80   33328  7424.00

Running (All Day) Statistics for Day 0 Body Weight

                         Mean      SD  Median  IQR
ISweekend.categorical
Weekday                166.76  219.48      97  148
Weekend                183.50  231.86     103  171

Scratching (All Day) Statistics for Day 0 Body Weight

                        Mean     SD  Median  IQR
ISweekend.categorical
Weekday                58.32  70.04      35   53
Weekend                61.66  71.07      39   53

Shaking (All Day) Statistics for Day 0 Body Weight

                        Mean     SD  Median  IQR
ISweekend.categorical
Weekday                28.65  16.60      25   22
Weekend                30.74  19.01      26   22

Sleeping (All Day) Statistics for Day 0 Body Weight

                           Mean       SD   Median      IQR
ISweekend.categorical
Weekday                48694.25  7021.16  48538.5  9005.75
Weekend                46781.33  7113.15  46771.0  9090.00

Walking (All Day) Statistics for Day 0 Body Weight

                          Mean       SD  Median      IQR
ISweekend.categorical
Weekday                4638.40  2100.66  4260.5  2552.25
Weekend                5023.25  2300.03  4708.0  3091.00

In [38]:
for activity in activities:
    print(f"{activity} Statistical Tests for Owner Daily Diary")
    statistical_tests(subgroup_df, activity, 'ISweekend.categorical')
    print("\n")

Resting (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Resting (All Day)' across 'ISweekend.categorical'
===========================================================
                        Statistic            P-value
-----------------------------------------------------------
Kruskal-Wallis Test 37.29740581078086 1.014194246668198e-09
-----------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Running (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Running (All Day)' across 'ISweekend.categorical'
=========================================================
                        Statistic           P-value
---------------------------------------------------------
Kruskal-Wallis Test 4.604037764474836 0.03189674865839526
---------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Scratching (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Scratching (All Day)' across 'ISweekend.categorical'
==========================================================
                        Statistic            P-value
----------------------------------------------------------
Kruskal-Wallis Test 3.2907004196979006 0.06967329481799124
----------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Shaking (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Shaking (All Day)' across 'ISweekend.categorical'
=========================================================
                        Statistic           P-value
---------------------------------------------------------
Kruskal-Wallis Test 3.799044670007224 0.05128183402406747
---------------------------------------------------------
We could not reject the null hypothesis. The medians of all groups are equal.


Sleeping (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Sleeping (All Day)' across 'ISweekend.categorical'
============================================================
                        Statistic             P-value
------------------------------------------------------------
Kruskal-Wallis Test 47.818220933183625 4.676257661985229e-12
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.


Walking (All Day) Statistical Tests for Owner Daily Diary
Kruskal-Wallis Test Results for 'Walking (All Day)' across 'ISweekend.categorical'
============================================================
                        Statistic            P-value
------------------------------------------------------------
Kruskal-Wallis Test 18.58798014951359 1.6224029082655578e-05
------------------------------------------------------------
We reject the null hypothesis. At least one group median is different from others.